### ISSUE TITLE
First letter is removed after selecting from autocomplete list

### ISSUE THREAD

**Issue by anjmao** [saibing/bingo#10]
In vscode with new master bingo version after I select something from autocomplete it removes first letter.
Example: trigget autompletefor builtin
```
append(slice []T, elems ...T)
```

Hit enter to select it. Result:

```
ppend(slice []T, elems ...T)
```

The same issue occurs for package names and local variables.

This issue occurs because of https://github.com/saibing/bingo/blob/master/langserver/completion.go#L59

It's a simple fix:
```go
insertText = insertText[len(prefix)-1:]
```

**Comment by saibing** [comment]
@anjmao 

thanks, I have apply your patch
