### ISSUE TITLE
False compile errors after some editing

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#104]
Tested with VS Code.

After some editing I start getting these non-sense (there is no error of course) messages:

![default](https://user-images.githubusercontent.com/6797881/52906964-73a9b480-3268-11e9-9a1b-7ddbf16e6ece.png)

![default](https://user-images.githubusercontent.com/6797881/52906984-dd29c300-3268-11e9-8f1b-87d7e7de2204.png)

This didn't appear earlier, so I think it's somehow connected with latest commits.

**Comment by exordium-frozen** [comment]
Facing the same issue.

The setup:

- **OS** - `macOS Mojave 10.14.3`
- **Go** - `1.11.5`
- **GO111MODULE** - *not set*
- **Client** - `VS Code 1.31`
- **vscode-go** - `0.9.2`
- Project uses **go modules**

Bingo Config:

- **Version** - `latest`

```
"go.languageServerFlags": [
    "-format-style=gofmt",
    "-cache-style=on-demand",
],
```

**Comment by quetz** [comment]
Having same issue. If I set `--cache-style=none` it goes away.

**Comment by nezorflame** [comment]
same issue, in my case it's `context.Context`

**Comment by lggomez** [comment]
It seems this is the same issue as #89

**Comment by saibing** [comment]
duplicated witch #89
