### ISSUE TITLE
"undefined" source of errors in VS Code

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#105]
Initially this issue was posted in _vscode-go_ repo, however they're saying that problem in LSP, refer https://github.com/Microsoft/vscode-go/issues/2321#issuecomment-464431006

![default](https://user-images.githubusercontent.com/6797881/52913022-8228b800-32ca-11e9-8b9d-cfda7cb981b4.png)

**Comment by ramya-rao-a** [comment]
This should be fixed in the latest [VS Code Insiders](https://code.visualstudio.com/insiders)

**Comment by mbana** [comment]
out of interest, @ramya-rao-a which paritcular commit fixed this?

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/issues/69091 is the tracking issue for this in VS Code.
It has the link to the commit that fixed the problem as well
