### ISSUE TITLE
Go to definition not working inside stdlib

### ISSUE THREAD

**Issue by s-kostyaev** [saibing/bingo#11]
When I go to definition into sdtlib package and see how it works inside sometime I want to go deeper. But bingo says that this package not inside GOPATH and not contain `go.mod`. Is it possible to make go to definition inside stdlib useful?

**Comment by s-kostyaev** [comment]
Now it works

**Comment by saibing** [comment]
@s-kostyaev 

there are some bugs on previous version. please update the last version

When open $GOROOT/src dir, bingo  takes 30 seconds to start up and takes up 3G of memory on my Windows 7 OS.

**Comment by s-kostyaev** [comment]
latest commit makes my client crazy (commented on commit). So I rollback to previous commit (latest - 1).

**Comment by saibing** [comment]
client crazy?

what's mean?

**Comment by s-kostyaev** [comment]
when I print `log` it prints `logloglog` or `llogoglog` or something like that.

**Comment by s-kostyaev** [comment]
it also can insert some autocompletion multiple times mixed up with other characters.

**Comment by s-kostyaev** [comment]
https://github.com/saibing/bingo/commit/331c8c1a657dca33faea8c97e97bd04ffabb359b - this is problematic commit
