### ISSUE TITLE
Completion adds extra zero to the end of the line

### ISSUE THREAD

**Issue by joncarr** [saibing/bingo#110]
When I complete a candidate the completion adds a literal `0` to the end of the line.  This behavior started after switching from go-langserver to bingo.  

As an example, if I type `fmt.Prin` and complete `Println` the resulting completion is
```
fmt.Println(a)0
```

OS: ArcoLinux
Editor: Emacs 26.1
Completion Backend: Company

**Comment by Jackson-soft** [comment]
same issue

![image](https://user-images.githubusercontent.com/3928114/52987857-e6b55580-3437-11e9-8532-3ffc454138d0.png)

**Comment by saibing** [comment]
@joncarr @Jackson-soft 

I can't reproduce the problem in vscode and coc.nvim, I won't use emacs, is it an issue handled by emacs lsp client?

**Comment by s-kostyaev** [comment]
It's issue on eglot & yasnippet side

**Comment by s-kostyaev** [comment]
But if change last tabstop from `${0}` to `$0` it will be fixed

**Comment by joncarr** [comment]
I don't use eglot, and I've used yasnippet for a long time without the extra zero being an issue.  So I'm unsure how it's an issue with any of those

**Comment by s-kostyaev** [comment]
@joncarr before this https://github.com/saibing/bingo/pull/68

**Comment by s-kostyaev** [comment]
@saibing looking into https://microsoft.github.io/language-server-protocol/specification#textDocument_completion we can do that:

>  But if change last tabstop from `${0}` to `$0` it will be fixed

I can create PR if you want.

**Comment by saibing** [comment]
@joncarr @s-kostyaev @Jackson-soft 

I have changed last tabstop from ${0} to $0. Please try the latest version bingo

**Comment by joncarr** [comment]
I have pulled the latest changes from master branch and installed the latest client.
```
git pull
GO111MODULE=on go install

**Comment by joncarr** [comment]
I have pulled the latest changes from master branch and installed the latest client.
```
git pull
GO111MODULE=on go install
```
And now the server will not start for me.  Just spins on `starting`

**Comment by saibing** [comment]
@joncarr 

please set flag: --trace, --logfile=/tmp/bingo.log, and then check /tmp/bingo.log.

**Comment by s-kostyaev** [comment]
@saibing fixed, thanks
