### ISSUE TITLE
大大好，go-mode中补全可不可以忽略大小写？

### ISSUE THREAD

**Issue by xep007** [saibing/bingo#112]
因为go可导出方法为大写字母开头，要输入大写字母才可补全，比如fmt.Println，输入fmt.之后要按大写的P才能弹出补全候选项，这样需要多按两次大写键或按住Shift键。能不能设置成补全忽略大小写呢？

**Comment by saibing** [comment]
@xep007 

你使用的是哪一款编辑器？vscode基本支持模糊选择的，包括忽略大小写的。

**Comment by xep007** [comment]
@saibing
我使用的是emacs。底下是lsp设置。
(use-package lsp-mode
     :diminish lsp-mode
     :hook (prog-mode . lsp)
     :init
     (setq lsp-auto-guess-root t)       ; Detect project root
     (setq lsp-prefer-flymake nil)      ; Use lsp-ui and flycheck
     :config
     ;; Configure LSP clients
     (use-package lsp-clients
       :ensure nil
       :init
       (setq lsp-clients-python-library-directories '("/usr/local/" "/usr/"))
       (setq lsp-clients-go-language-server-flags
             '("-gocodecompletion" "--format-style=\"goimports\""))))

   (use-package lsp-ui
     :bind (:map lsp-ui-mode-map
                 ([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
                 ([remap xref-find-references] . lsp-ui-peek-find-references)
                 ("C-c u" . lsp-ui-imenu)))
   ;; :config
   ;; (setq lsp-ui-sideline-enable nil)
   ;; (setq lsp-ui-doc-enable nil))


   (use-package company-lsp)

   ;; C/C++/Objective-C support
   (use-package ccls
     :defines projectile-project-root-files-top-down-recurring
     :hook ((c-mode c++-mode objc-mode cuda-mode) . (lambda ()
                                                      (require 'ccls)
                                                      (lsp)))
     :config
     (with-eval-after-load 'projectile
       (setq projectile-project-root-files-top-down-recurring
             (append '("compile_commands.json"
                       ".ccls")
                     projectile-project-root-files-top-down-recurring))))

   ;; Java support
   (use-package lsp-java
     :hook (java-mode . (lambda ()
                          (require 'lsp-java)
                          (lsp))))
   ))

**Comment by saibing** [comment]
@xep007 

There is no flag "-gocodecompletion" for bingo.

**Comment by xep007** [comment]
@saibing 
我把lsp-clienst和lsp-ui包都注释掉也还是一样。也许是lsp的问题也有可能。

**Comment by saibing** [comment]
@xep007 

因为后多数客户端，如vscode, coc.nvim都能很好的支持在客户端实现忽略大小写的补全，bingo服务端不再重复实现这个功能了。

**Comment by xep007** [comment]
谢谢saibing!  在company-lsp中将company-lsp-cache-candidates设置为'auto即可。

**Comment by sandao** [comment]
> 谢谢saibing! 在company-lsp中将company-lsp-cache-candidates设置为'auto即可。

我也遇到你了你这个问题，但是按照上面的设置无效。请问你后面有再出现这个问题么？

**Comment by xep007** [comment]
抱歉，很久没上mail。
我设置‘auto后，不再有问题。






在 2019-04-21 16:18:54，"sandao" <notifications@github.com> 写道：


谢谢saibing! 在company-lsp中将company-lsp-cache-candidates设置为'auto即可。

我也遇到你了你这个问题，但是按照上面的设置无效。请问你后面有再出现这个问题么？
