### ISSUE TITLE
Question about error handling during completion

### ISSUE THREAD

**Issue by fjl** [saibing/bingo#115]
I've been using bingo through emacs for one day and it works really well! There is only one minor
annoyance: completion sometimes displays warnings in the editor when bingo doesn't know how to handle a certain file position. The specific warning I'm talking about is

```text
this is a definition, of func (*foo ).bar(_ invalid type, ...) error
```

Would it be better to log completion errors to stderr instead of returning them as
an error response? I can send a PR to do this, just wanted to ask first because there might
be a good reason to return them to the client.

**Comment by fjl** [comment]
Maybe this should also be fixed upstream. It doesn't really make sense to reject completion in definition context. If you are writing a method definition like 

```text
func (f *foo) bar
```

it should complete known method names in scope instead.

**Comment by saibing** [comment]
@fjl 

Please try the latest version bingo

**Comment by fjl** [comment]
This is not fixed, I still see the same error even with the latest version of bingo.
