### ISSUE TITLE
vscode-go instruction not working

### ISSUE THREAD

**Issue by jackielii** [saibing/bingo#124]
The instructions for vscode-go is not correct. The one in wiki works: https://github.com/saibing/bingo/wiki/Language-Client#vscode-go

```
{
    "go.useLanguageServer": true,

    "go.alternateTools": {
        "go-langserver": "bingo"
    },

    "go.languageServerFlags": [],

    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    }
}
```

**Comment by saibing** [comment]
@jackielii

I tested bingo with flag '-enhance-signature-help' is ok.

Which version of bingo that you used?

**Comment by jackielii** [comment]
Hi, I think I know what's wrong, I used `go install` directly and that chose a different version.
