### ISSUE TITLE
panic with pure main package out of gopath

### ISSUE THREAD

**Issue by shuxiao9058** [saibing/bingo#126]
LSP :: unexpected panic: runtime error: invalid memory address or nil pointer dereference
Quit

**Comment by saibing** [comment]
@shuxiao9058 

Please set bingo's flag "--trace", "--logfile=/tmp/bingo.log", and get more information about this panic.

**Comment by saibing** [comment]
@shuxiao9058 

you should use [go module project](https://github.com/golang/go/wiki/Modules)

**Comment by shuxiao9058** [comment]
The same error, and the go files in my package is all `package main`.

**Comment by saibing** [comment]
@shuxiao9058 

Is the 'go build' command run successfully?

**Comment by shuxiao9058** [comment]
yes

**Comment by saibing** [comment]
@shuxiao9058 

Please show me the full /tmp/bingo.log from bingo startup.

**Comment by Jackson-soft** [comment]
same issue

**Comment by saibing** [comment]
@shuxiao9058 

Please try the latest bingo, and git me more detail information.

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/54121895-8f9f1100-4436-11e9-9168-4fe16b5b69fa.png)


![image](https://user-images.githubusercontent.com/3928114/54121913-9a59a600-4436-11e9-8602-0568e7497e5e.png)

**Comment by shuxiao9058** [comment]
always the same error. @saibing

**Comment by shuxiao9058** [comment]
Can you provide your email address? And then I send the log file to your email, since the project is the company's project. @saibing

**Comment by saibing** [comment]
@shuxiao9058 
pls send to my email saibing@live.com

**Comment by shuxiao9058** [comment]
@saibing please check email.

**Comment by shuxiao9058** [comment]
跟踪了一下看是[L178](https://github.com/golang/tools/blob/1286b2016bb195031cab5657d3244bc996b3f2dd/go/packages/packages.go#L178)这一行
的`response.Roots`为nil。

@saibing

**Comment by shuxiao9058** [comment]
panic with cgo
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
get token failed: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- /Users/jiya/workspace/exec]: exit status 2: # github.com/shuxiao9058/exec/internal/test
...
...
Undefined symbols for architecture x86_64:
```

```
LSP :: package is null for file file:///Users/jiya/workspace/exec/main.go
LSP :: token file does not exist of file:///Users/jiya/workspace/exec/main.go
```

**Comment by shuxiao9058** [comment]
@saibing 已确认是cgo不同平台的问题，添加对应方法wrapper解决了。
