### ISSUE TITLE
collaborating on golsp

### ISSUE THREAD

**Issue by stamblerre** [saibing/bingo#13]
Hi @saibing! I'm one of the people currently working on [golang.org/x/tools/cmd/golsp](https://golang.org/x/tools/cmd/golsp). We recently noticed and were excited to see your work on bingo. Our plan for golsp is for it to become the official language server supported by the Go team, and the folks at Sourcegraph have agreed that they would eventually like to use our code once it is ready. 

We noticed that a lot of the code in this repository is shared with golsp and with [go-langserver](https://github.com/sourcegraph/go-langserver), so we were wondering if you would be interested in collaborating with us on golsp. More information about golsp can be found through the various channels listed [here](https://github.com/golang/go/wiki/golang-tools). If you'd like to continue this conversation, I'm happy to talk on this issue or via email (rstambler@golang.org).

**Comment by anjmao** [comment]
@stamblerre My suggestion is to move golsp to `golang/lsp` or `golang/golsp`. That repository `golang/tools` is really annoying because:
1)  It's not possible to register new issues directly on tools repo.
2) Source code is published to golang.org/x/tools/cmd/golsp. Why not just use github and `github.com/golang/golsp` url? 
3) How do you tag new releases and do versioning? Separate repo for golsp would allow to have github release tags.

I really like how easy it is to test bingo and rise new issues directly on this repo. Feedback loop is super fast.

**Comment by seagle0128** [comment]
Hi guys,

I am so exciting seeing this conversation. My questions is if it's possible to merge to ONE REAL OFFICIAL LSP project? I was enjoying `go-langserver` but it's deprecated, then I found `bingo`, now `golsp`. Go developers really need a stable and fast langserver, like other languages. Appreciate your contributions, and I'd like contribute if possible.

**Comment by saibing** [comment]
@seagle0128 

I will invest in the development of golsp in the near future, but at present I focus on solving some problems with bingo.

**Comment by stamblerre** [comment]
Our intention is for golsp to be the official Go language server implementation, supported by the Go tools team. Obviously other language servers may continue to exist, but once we officially release golsp, we will continue to actively maintain it.

**Comment by mbana** [comment]
@stamblerre @saibing 

Some things that I think different (Go) implementations might be benefit from:

* Shared integration test suite: `go-langserver`, `bingo` and `gopls` would then, in theory, not have to re-write custom integration tests.
* Package for the protocol: Currently there is https://github.com/sourcegraph/go-lsp which `go-langserver` and `bingo` both use, and there is https://github.com/golang/tools/tree/master/internal/lsp/protocol which `gopls` uses.

As an aside, and I don't mean this in a bad way, `gopls` is hard to get started with. Where are the instructions for installing it?

Do you use `golsp` to develop `golsp`?

**Comment by stamblerre** [comment]
- We are definitely going to work on integration tests for gopls, which other server implementations are welcome to use. However, it's worth noting that gopls will ultimately replace go-langserver (as discussed with the Sourcegraph folks).
- A member of the Go team is actually currently working on automatically generating https://github.com/golang/tools/tree/master/internal/lsp/protocol from the LSP spec.
- When gopls is more usable, I will share instructions on how to get started with it. For now, the best way to set it up is through VSCode, by using the "go.alternateTools" setting. For example:

```json
"go.alternateTools": {
     "go-langserver": "$GOPATH/bin/gopls"
}
```

- I do use gopls when developing gopls, yes.

**Comment by saibing** [comment]
@stamblerre  @stamblerre @imjustfly @anjmao @seagle0128

I have ported some features such as references, rename, workspace symbol, implementation of bingo to gopls.

If you want to use the enhanced version of gopls, try https://github.com/saibing/tools.

Now, Maybe I can do something for gopls.  I hope that we will eventually have a unified language server: gopls.

**Comment by stamblerre** [comment]
Thanks for your work, @saibing! Looking forward to collaborating.

**Comment by jan-xyz** [comment]
May I ask what's the best way for us in the community to follow along with the progress?

**Comment by inliquid** [comment]
Shit show.

**Comment by saibing** [comment]
@jan-xyz 

Now, you can try the enhanced version gopls: [https://github.com/saibing/tools](https://github.com/saibing/tools). 

I will keep this gopls in sync with Google's official [gopls](https://github.com/golang/tools/blob/master/cmd/gopls/main.go) until the official gopls become fully functional and stable.

**Comment by stamblerre** [comment]
To add to that, updates on gopls can be found here: https://github.com/golang/go/wiki/gopls.

**Comment by webframp** [comment]
Really looking forward to the collaboration, right now gopls (and the fork) does not provide useful interaction with [lsp-mode](https://github.com/emacs-lsp/lsp-mode) for me. 

For example, compare the lsp-ui hover when using`bingo`:
<img width="1608" alt="Screen Shot 2019-04-10 at 13 18 30" src="https://user-images.githubusercontent.com/774378/55900296-d9455d80-5b94-11e9-90e1-9ed186165737.png">

With how `gopls` looks:
<img width="1633" alt="Screen Shot 2019-04-10 at 13 20 29" src="https://user-images.githubusercontent.com/774378/55900332-ee21f100-5b94-11e9-8a95-e6295ca3263c.png">

**Comment by saibing** [comment]
@webframp 

The fork [gopls](https://github.com/saibing/tools) has fixed it

**Comment by webframp** [comment]
Thanks @saibing!

**Comment by yzliu** [comment]
Thanks @saibing!
