### ISSUE TITLE
token file does not exist of file

### ISSUE THREAD

**Issue by ecx** [saibing/bingo#131]
Hello! I am newbie to bingo, how to make it work? I am try to use it in vim 8 with "vim-go" and "LanguageClient-neovim" and most actions always get:
`[LC] Error: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "token file does not exist of file:///home/ecx/go_test/hello-world.go", data: None }, id: Num(2) }`
vim's embedded omni completion works good, but it is not a work of bingo. Can you explain, please, what token files it talking about?

**Comment by saibing** [comment]
@ecx 

you should use [go module project](https://github.com/golang/go/wiki/Modules)

Please set bingo's flag "--trace", "--logfile=/tmp/bingo.log", and show me the full /tmp/bingo.log from bingo startup. 

thanks

**Comment by ecx** [comment]
`langserver-go: reading on stdin, writing on stdout
  --> request #1: initialize: {"capabilities":{"textDocument":{"colorProvider":null,"completion":{"completionItem":{"snippetSupport":false}},"signatur  eHelp":{"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynami  cRegistration":true}}},"processId":27782,"rootPath":"/home/ecx/go_test","rootUri":"file:///home/ecx/go_test","trace":"off"}
  Passing an initialize rootPath URI ("file:///home/ecx/go_test") is deprecated. Use rootUri instead.
  <-- notif: window/logMessage: {"type":3,"message":"GOPATH: [/home/ecx/go], import path: "}
  <-- notif: window/logMessage: {"type":3,"message":"GO111MODULE=auto, module mode"}
  <-- notif: window/showMessage: {"type":3,"message":"load /home/ecx/go_test successfully! elapsed time: 0 seconds, cache: false, go module: false."}
  <-- result #1: initialize: {"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHel  pProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"referencesProvider":true,"documentSymbolProvider  ":true,"workspaceSymbolProvider":true,"implementationProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"rename  Provider":true,"xworkspaceReferencesProvider":true,"xdefinitionProvider":true,"xworkspaceSymbolByProperties":true}}
  --> notif: initialized: {}
`
