### ISSUE TITLE
some packages seem to break bingo

### ISSUE THREAD

**Issue by dsvensson** [saibing/bingo#137]
I have some dependency of one of my dependencies that seems to break bingo, not sure why:

This is the output of my log:
```
notify: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- /some/path/to/my/project/...]: exit status 1: go: github.com/globalsign/mgo@v0.0.0-20181015135952-eeefdecb41b8: /path/to/my/gopath/pkg/mod/cache/vcs/a6f30753f09f9965ec97c58b60d35441dc379255da2d413e0d7ce71487babf0b.info exists with wrong content (have "" want "git2:https://github.com/globalsign/mgo")
go: github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb: /path/to/my/gopath/pkg/mod/cache/vcs/a6f30753f09f9965ec97c58b60d35441dc379255da2d413e0d7ce71487babf0b.info exists with wrong content (have "" want "git2:https://github.com/globalsign/mgo")
go: error loading module requirements
```

Tried adding a replace in my go.mod, which caused my go.sum to contain the correct version of that package (now pointing to a version that has a go.mod file), but the error message from bingo remains the same.

The specific mgo/bson version is pulled in by go-openapi/runtime.

**Comment by dsvensson** [comment]
Removed my pkg directory and the override to the mgo branch containing a go.mod fixed the problem. So I guess there's not much bingo can do here. I just have to continue file issues around the planet until everyone is go.mod-enabled?

**Comment by saibing** [comment]
@dsvensson 

You should make sure that the go list command works correctly and that bingo will work properly.
