### ISSUE TITLE
Autocomplete doesn't add imports

### ISSUE THREAD

**Issue by nezorflame** [saibing/bingo#145]
Following the https://github.com/saibing/bingo/issues/54, the autocompletion itself works. It's very fast, thanks for that.
But it doesn't add the autocompleted import to the `import` section (except for the stdlib packages, which are added only after the `Save` action which is also non-ideal).
This renders this very useful feature almost useless. Am I missing something or this is not implemented yet?

My setup:
- VSCode Go `0.9.3-beta.2`
- latest `bingo` from master

My config:

```json
"go.useLanguageServer": true,
"go.alternateTools": {
    "go-langserver": "bingo"
},
"go.languageServerFlags": [
    "--diagnostics-style=instant",
    "--enhance-signature-help",
    "--format-style=goimports",
    "--goimports-prefix='github.com/nezorflame'",
],
"go.languageServerExperimentalFeatures": {
    "autoComplete": true,
    "documentSymbols": true,
    "findReferences": true,
    "format": true,
    "goToDefinition": true,
    "goToTypeDefinition": true,
    "hover": true,
    "rename": true,
    "signatureHelp": true,
    "workspaceSymbols": true,
}
```

**Comment by nezorflame** [comment]
Can anyone confirm this?

**Comment by inliquid** [comment]
I can confirm, that after adding any autocompeled suggestion, I have to press 'Alt-Shift-F' to enforce addition of import (is done by bingo as well - based on `goimports` logic, but formatting is delegated to bingo).

I think bingo should add imports automatically.

**Comment by saibing** [comment]
@nezorflame @inliquid 

Please use the enhanced version of [gopls](https://github.com/saibing/tools), it has supported this feature.
