### ISSUE TITLE
Duplicate error in VSCode

### ISSUE THREAD

**Issue by nezorflame** [saibing/bingo#146]
Almost every error is duplicated in the `Problems` section (cc @ramya-rao-a):

![image](https://user-images.githubusercontent.com/3906766/54119886-80549f00-4407-11e9-91e1-304dfe4d5de4.png)

**Comment by ramya-rao-a** [comment]
@saibing Does bingo report any errors that the vscode-go extension doesnt? If not, then I'll be updating the extension to ignore the diagnostics from bingo

**Comment by saibing** [comment]
@nezorflame 

The second error come from 'go build' command that  "go.buildOnSave" flag can turn on or turn off.

**Comment by saibing** [comment]
@ramya-rao-a 

no, bingo only report the same error as 'go build' command.

**Comment by nezorflame** [comment]
Thanks @saibing @ramya-rao-a I'll use `-diagnostics-style=none` for the time being (since it's broken right now anyway, see #89)

**Comment by ramya-rao-a** [comment]
@nezorflame Is that a flag to be passed to bingo?

**Comment by nezorflame** [comment]
@ramya-rao-a yes, in the `"go.languageServerFlags"` slice

**Comment by ramya-rao-a** [comment]
Ah, understood.

**Comment by inliquid** [comment]
Strange, but in my case I don't see any LSP compiler errors with latest version of bingo, I thought it was disabled for some reason... `-diagnostics-style` unset.
