### ISSUE TITLE
Bingo does not provide suggestions for unimported packages

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#147]
VS code. Using latest version of bingo, I found that it has stopped providing suggestions on unimported packages. No idea when this was broken.
![изображение](https://user-images.githubusercontent.com/6797881/54242300-1fc38000-4535-11e9-8b1f-a19348c4fda3.png)

**Comment by saibing** [comment]
@inliquid 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
