### ISSUE TITLE
completion of constant has a problem

### ISSUE THREAD

**Issue by imjustfly** [saibing/bingo#15]
When bingo try complete a constant, it returns a full assignment statement.

Fro example:

```go
const foo = 100

func main() {
    test := f // wait for completion
}
```
bingo will give me  `foo = 100` as a completion item instead `foo`:

```go
const foo = 100

func main() {
    test := foo = 100
}
```

I use neovim with LanguageClient-Neovim.

**Comment by saibing** [comment]
@imjustfly 
thanks your feedback.

I will fix this bug on the weekend.
