### ISSUE TITLE
token file not exist

### ISSUE THREAD

**Issue by taigacute** [saibing/bingo#153]
## environment
macos
## Go version
1.12.1
## Tool
neovim 0.4-dev
## Problem
i use coc。and this is a go mod project。but  i got these messages  like this pic
![123](https://user-images.githubusercontent.com/41671631/54434851-225aeb00-476a-11e9-8f37-ee525db6735e.png)
## log
[bingo.log](https://github.com/saibing/bingo/files/2971320/bingo.log)

**Comment by saibing** [comment]
@taigacute 

Please try the latest's bingo

**Comment by taigacute** [comment]
@saibing  thanks for your work, another question, i make a new file in nerdtree then i edit this file ,bingo cant work with new file.   input`package xxx` then save it and reopen this file.bingo worked.
i will try latest bingo。
