### ISSUE TITLE
can't autocomplete new import packages

### ISSUE THREAD

**Issue by chenjie199234** [saibing/bingo#156]
```
package main
import (
       "fmt"
)
func main(){
        fmt.Println("hello world!")
}
```
here is the start code.
when i import a new package like "math/rand"
the rand package can't be auto completed
```
package main
import (
        "fmt"
        "math/rand"
)
func main(){
        fmt.Println("hello bingo!")
        rand.
        (it will bot be auto completed here.)
}
```
when i close the file and reopen it.it works again.

Editor:neovim 0.3.4
lsp:w0rp/ale

**Comment by malexdev** [comment]
I am also having this issue.
After importing, if you type a symbol from the package manually then save the file, autocompletes will work going forward.

**Comment by saibing** [comment]
@chenjie199234 @malexdev 

The root cause of this problem is: [bad import code](https://github.com/saibing/bingo/blob/master/langserver/internal/source/completion.go#L186)

**Comment by saibing** [comment]
@chenjie199234 

Please use the enhanced version of [gopls](https://github.com/saibing/tools), it has fixed this issue.

**Comment by malexdev** [comment]
@saibing: just to confirm, in order to use your updates to gopls we need to install your version, not the official one? 

If so: Do you and the Go team have plans to integrate your fixes to gopls, or is this probably going to stay the way it is?
