### ISSUE TITLE
 resolve request support

### ISSUE THREAD

**Issue by taigacute** [saibing/bingo#157]
使用coc 与neovim的float window。有时可以返回doc 在floatwindow显示，有时没有。查看output发现并不是所有返回都会带doc 是否做了判断呢？支持resolve 请求和doHover特性是否更好？
![image](https://user-images.githubusercontent.com/41671631/54474264-f600a680-481d-11e9-8152-bdadb3966999.png)

**Comment by taigacute** [comment]
另一个问题。没有错误返回。

**Comment by saibing** [comment]
@taigacute 

图片太模块了，看不清楚问题。我使用coc.nvim，hover的浮动窗口显示是可以的。

你设置一下 --trace, 看一下跟踪日志有什么异常没有？

**Comment by taigacute** [comment]
@saibing  我在特定的snippets中，可以查看到方法的doc在floatwindow，例如这样:
![1](https://user-images.githubusercontent.com/41671631/54863708-e1c12a00-4d86-11e9-89b1-88d58f08eeaf.png)
是否是判断了code的状态？忙碌的时候不返回doc？查看了output 有时候返回有时候不返回
关于hover。bingo 支持lsp的feature我是看到有支持hover的，但是我通过coc的showdoc方法 我不是在floatwindow得到doc 而是一个窗口。
![12](https://user-images.githubusercontent.com/41671631/54863735-48dede80-4d87-11e9-9533-81d30a9ed2c8.png)

**Comment by saibing** [comment]
@taigacute 

这应该是coc.nvim的bug, 因为bingo的hover功能在vscode中使用非常正常.

另外我已经不再维护bingo, 它的大部分功能我已经移植到[gopls](https://github.com/saibing/tools), 您可以试用一下这个新版本的gopls

**Comment by glepnir** [comment]
@taigacute  thanks for your reply。我会尝试用下gopls 之前用过 bug 太多。如果要写一个go的lsp我需要使用哪些包 ？
