### ISSUE TITLE
code formatting always changes vim buffer after saving.

### ISSUE THREAD

**Issue by imjustfly** [saibing/bingo#16]
After I save a go buffer with `:w`， the buffer is always modified by bingo's code formatting even if there is nothing changed. 

This will make buffer in modified state all the time. You can't close the buffer by `:q`, only `:wq` works.

**Comment by saibing** [comment]
@imjustfly 

thanks your feedback.

I will fix this bug on the weekend.

**Comment by imjustfly** [comment]
@saibing This issue reappears on latest  master.
