### ISSUE TITLE
Add format-tool Flag

### ISSUE THREAD

**Issue by Starz0r** [saibing/bingo#163]
I believe adding `-format-tool` is the only stopper for making this work with Atom related IDE packages. Is it possible to get this added in bingo? I referenced this in issue #61, but I don't think you saw it, so I wanted to bring it up in a specific issue instead of a broad one.

**Comment by saibing** [comment]
@Starz0r 

pls see ckaznocha/ide-go#42

**Comment by saibing** [comment]
@Starz0r 

any update?

**Comment by Starz0r** [comment]
It did not solve my issue. Auto-completion, Linting, and Suggestions did not work when disabling those two, but it did stop bingo from crashing when starting. So it's something, I guess, but I wouldn't say it's a solution.

**Comment by Starz0r** [comment]
I also have to imagine the crashing is because `-diagnostics` is a flag that for bingo is unsupported. So maybe implementing either of these may fix it. If this is a fork of go-langserver, then I have to imagine that these two flags were ripped out for some reason. If you removed these, is there a reason why you did that?

**Comment by saibing** [comment]
@Starz0r 

bingo is not a go-langserver compatible fork version. I added these parameters, you can try the latest version of bingo
