### ISSUE TITLE
Bingo does not update diagnostics after saving

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#165]
VS Code,
![изображение](https://user-images.githubusercontent.com/6797881/54649872-f9658d80-4abc-11e9-9b17-12968a916869.png)

**Comment by saibing** [comment]
@inliquid 

Please set -diagnostics-style=instant.

if -diagnostics-style=onsave, diagnostics will not be updated in real time until the next save action.

**Comment by inliquid** [comment]
@saibing Bingo does not update diagnostics after saving by
- `Ctrl-S`
- `Save File` from Command pallete
![изображение](https://user-images.githubusercontent.com/6797881/54867078-41223880-4d8d-11e9-89b8-22b72c7b9083.png)

**Comment by inliquid** [comment]
Actually `instant` is set by default, and I didn't touch this param:
```
-diagnostics-style string
        diagnostics style: none, instant, onsave. Can be overridden by InitializationOptions. (default "instant")
```
@saibing

**Comment by saibing** [comment]
@inliquid 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
