### ISSUE TITLE
auto completion doesn't work inside Goroutines.

### ISSUE THREAD

**Issue by OneOfOne** [saibing/bingo#166]
Related:

- https://github.com/golang/go/issues/29313
- https://github.com/golang/go/issues/30805

**Comment by saibing** [comment]
@OneOfOne 

bingo's auto completion works well inside Goroutine.

Can you give me a specific scene example that bingo does not?

**Comment by OneOfOne** [comment]
```
┏━ oneofone@Ava ❰✪/s/bingo❱ ❰master|✔❱
┗━● git describe --always
65a1d72 << bingo commit

┏━ oneofone@Ava ❰/t/x❱
┗━● cat go.mod
module x
go 1.13

┏━ oneofone@Ava ❰/t/x❱
┗━● cat main.go
package main

import "bufio"

func main() {
	br := bufio.NewReader(nil)
	go func() {
		br.
	}()
}
```

![Screenshot_20190321_195457](https://user-images.githubusercontent.com/1080443/54773939-4fe4e000-4c13-11e9-9200-61b7930077da.png)
![Screenshot_20190321_195515](https://user-images.githubusercontent.com/1080443/54773940-507d7680-4c13-11e9-8b02-e0ff4d9083eb.png)

**Comment by OneOfOne** [comment]
Looking at vscode `go-langserver`'s output, I got this:

```
[Error - 7:59:54 PM] Request textDocument/signatureHelp failed.
  Message: the enclosing function is malformed
  Code: 0 
[Error - 8:00:01 PM] Request textDocument/formatting failed.
  Message: /tmp/x/main.go:9:2: expected selector or type assertion, found '}' (and 1 more errors)
  Code: 0 
```

**Comment by OneOfOne** [comment]
removing the `go` keyword fixes it.

**Comment by inliquid** [comment]
Same in `defer` statements.

**Comment by imjustfly** [comment]
According to https://github.com/golang/go/issues/29313, this is a special case, which needs workaround.

**Comment by saibing** [comment]
@OneOfOne @inliquid  @imjustfly 

I have fixed it, please try latest version bingo.

**Comment by oblitum** [comment]
Maybe this issue has some relation with [this other](https://github.com/saibing/bingo/issues/135#issuecomment-470778371).
