### ISSUE TITLE
Implement diagnostics range

### ISSUE THREAD

**Issue by inoc603** [saibing/bingo#167]
It seems that gopls has implemented range in diagnostics https://github.com/golang/tools/blob/master/internal/lsp/diagnostics.go

Maybe it's time to update [langserver/diagnostics.go](https://github.com/saibing/bingo/blob/master/langserver/diagnostics.go) accordingly to bring that feature to bingo? Thanks.

**Comment by saibing** [comment]
@inoc603 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)

**Comment by inoc603** [comment]
Cool. Any chance it will be merged into gopls? Will this version of gopls stay up to date with the official gopls repo?
