### ISSUE TITLE
Imported a new package cannot be completed.

### ISSUE THREAD

**Issue by taigacute** [saibing/bingo#169]
## environment
* Mac os 10.13.6
* Go version : 1.12.1
* NVIM v0.4.0-436-g3e78319ac
## Problem 
I cant got any completeitem when i import a new package. After i save the file and reopen this file it works .i try gomod project and not gomod project . also problem
![go](https://user-images.githubusercontent.com/41671631/54880892-187d6a00-4e85-11e9-81fb-f38ec0061dd3.gif)
## output
i use coc.nvim .use `cocinfo` to checkout lsp. i got nothin in bingo
![11](https://user-images.githubusercontent.com/41671631/54880906-3519a200-4e85-11e9-9ef6-a783c93515d6.png)

**Comment by JayceCao** [comment]
Got the same problem with neovim 0.3.4-2 on Arch Linux.

**Comment by saibing** [comment]
duplicated with #156
