### ISSUE TITLE
Getting document symbols is very slow

### ISSUE THREAD

**Issue by fjl** [saibing/bingo#176]
My editor fetches the list of symbols in the document every time I open a file. If I'm reading the code correctly, getting the symbols of the current document loads/typechecks the file's package and all dependency packages.

Getting symbols in a file doesn't need the package and could be much faster. It really only requires walking the AST. The containing package doesn't even need to be typechecked for this.

**Comment by saibing** [comment]
@fjl 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
