### ISSUE TITLE
Bingo stops providing any diagnostics

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#177]
VS Code. Diagnostics params untouched (`instant` by default). After some coding it just stops providing of any diagnostics information (compile errors) at all. No reaction to `Ctrl-S` or `Alt-Shift-F`:
![изображение](https://user-images.githubusercontent.com/6797881/55238333-4e379f80-5245-11e9-8ca9-05ec2fbabae9.png)

**Comment by saibing** [comment]
@inliquid 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
