### ISSUE TITLE
Add possibility to control diagnostics scope

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#178]
At the moment user can't choose wether Bingo will provide 'workspace' or 'package'-wide diagnostics. I think the scope should be controlled like in VS Code, with at least two options: 'workspace' and 'package':
![изображение](https://user-images.githubusercontent.com/6797881/55238688-2d237e80-5246-11e9-9834-8a6d0ac66048.png)

**Comment by saibing** [comment]
@inliquid 

both bingo and gopls only support package level diagnostics scope by far. gopls maybe will support the workspace level diagnostics scope.

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
