### ISSUE TITLE
Incorrect import paths in quick documentation

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#179]
VS Code. In many different cases (not only this example) Bingo omits import paths prefixes when providing quick documentation response, like if some argument was part of the package of function/method being explored, when he is not, in fact. This adds a lot of confusion when reading quick documentation. In the following example return argument must be of type `func(*js.Object)`, not `func(*Object)`
![изображение](https://user-images.githubusercontent.com/6797881/55244700-b8a30c80-5252-11e9-8eb7-62b2e662f372.png)

**Comment by saibing** [comment]
@inliquid 

Please use the enhanced version of [gopls](https://github.com/saibing/tools)
