### ISSUE TITLE
unknown type name double_t on mac os x10.13.2

### ISSUE THREAD

**Issue by ofttryaj** [saibing/bingo#182]
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/fp.h
error: unknown type name double_t

**Comment by saibing** [comment]
@ofttryaj 

fp.h is a c/c++ header file, so I think this error come from c/c++ language server, not bingo.

**Comment by ofttryaj** [comment]
I use go install command to install gopls, it shows me the error messages
![image](https://user-images.githubusercontent.com/15887451/55370632-a7e1e780-552d-11e9-92e0-d873f6a30ce3.png)

**Comment by saibing** [comment]
@ofttryaj 

I has fixed the issue, please try the latest version gopls: [https://github.com/saibing/tools](https://github.com/saibing/tools)

**Comment by ofttryaj** [comment]
@saibing Thank you very much! It works

**Comment by ofttryaj** [comment]
@saibing Can you tell me why I can not install https://github.com/saibing/tools before you fix it

**Comment by saibing** [comment]
@ofttryaj 

I'm has used [github.com/fsnotify/fsevents](https://github.com/fsnotify/fsevents) that use some cgo code.
