### ISSUE TITLE
no packages found for nested module

### ISSUE THREAD

**Issue by s-kostyaev** [saibing/bingo#2]
Hi! Thanks for great job!
I'm not sure, but I think your lsp server should handle configuration like this:
```
big_project
|
+- go.mod
|
`-subproject
    |
    `- go.mod
```
in second `go.mod`:
```
module github.com/someuser/big_project/subproject

replace github.com/someuser/big_project v0.1.0 => ../
```
because `go build` for subproject are fine and bingo:
```
no packages found for /Users/someuser/projects/big_project/subproject/cmd/main.go
```

PS. My client set project root to `big_project` directory

**Comment by saibing** [comment]
@s-kostyaev 
thanks, I didn't notice this scene. I will solve the problem as soon as possible.

**Comment by s-kostyaev** [comment]
@saibing for now it works for me after this patch:
```
diff --git a/langserver/internal/source/command.go b/langserver/internal/source/command.go
index bf7164c..b0de27c 100644
--- a/langserver/internal/source/command.go
+++ b/langserver/internal/source/command.go
@@ -9,7 +9,7 @@ import (
 )
 
 // invokeGo returns the stdout of a go command invocation.
-func invokeGo(ctx context.Context, dir string,  args ...string) (*bytes.Buffer, error) {
+func invokeGo(ctx context.Context, dir string, args ...string) (*bytes.Buffer, error) {
        stdout := new(bytes.Buffer)
        stderr := new(bytes.Buffer)
 
@@ -32,9 +32,9 @@ func invokeGo(ctx context.Context, dir string,  args ...string) (*bytes.Buffer,
                }
        }
 
-       if len(stderr.Bytes()) != 0 {
-               return nil, fmt.Errorf("'go %v' failed: %s", args, string(stderr.Bytes()))
-       }
+       // if len(stderr.Bytes()) != 0 {
+       //      return nil, fmt.Errorf("'go %v' failed: %s", args, string(stderr.Bytes()))
+       // }
 
        return stdout, nil
-}
\ No newline at end of file
+}
```
Maybe you should log warning instead of returning error in this case?
Hint: case is on `langserver/internal/source/module_cache.go:73`:
`buf, err := invokeGo(context.Background(), m.gomodDir, "list", "-m", "-json", "all")`
this command returns non-empty stderr, but it's fine.

**Comment by s-kostyaev** [comment]
Also is there any option to store project cache on disk (with checks and invalidation)? Init time is so long.

**Comment by saibing** [comment]
@s-kostyaev 
I have implement support nested module, please try the latest version.

bingo can not store project cache on disk by far.

- How long the init time of your project?

- What size of your project's code?

**Comment by s-kostyaev** [comment]
@saibing Thank you.

without my patch from https://github.com/saibing/bingo/issues/2#issuecomment-442739584 it doesn't work on my project, because `go list -m -json all` inside `subproject` prints `go: finding github.com/someuser/big_project v0.1.0` to stderr.

I'll try to reply to your other questions as soon as possible.

**Comment by saibing** [comment]
@s-kostyaev 

thanks , I have apply your patch.

**Comment by s-kostyaev** [comment]
> How long the init time of your project?

about 3-5 min

> What size of your project's code?

by `https://github.com/hhatto/gocloc` 13206 loc without deps, 84562 with `go mod vendor` and I don't know how to count loc used from stdlib.

**Comment by s-kostyaev** [comment]
> thanks , I have apply your patch, please try again.

This problem is solved. There is some other problems, but I'll try to collect more information before I can report it.

@saibing thanks

**Comment by saibing** [comment]
> > How long the init time of your project?
> 
> about 3-5 min
> 
> > What size of your project's code?
> 
> by `https://github.com/hhatto/gocloc` 13206 loc without deps, 84562 with `go mod vendor` and I don't know how to count loc used from stdlib.

for my project without deps: 
```txt
http://cloc.sourceforge.net v 1.64  T=11.30 s (232.9 files/s, 41125.1 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
Go                                2085          45672          22801         256325
```
The bingo's init time is 20 seconds.

So, there are may be some thing wrong:

1. The performance of your disk io?

2. Is bingo waiting for download deps module code from internet on invoke go list command?

**Comment by s-kostyaev** [comment]
> The performance of your disk io?

I test it on macbook pro with ssd

> Is bingo waiting for download deps module code from internet on invoke go list command?

all dependencies already downloaded.

But I see about 2,5 GB of memory usage by bingo and 3 GB swapped memory, so maybe problem with os x memory scheduler.

**Comment by s-kostyaev** [comment]
@saibing with other client (https://github.com/emacs-lsp/lsp-mode) init time is 70 seconds.
