### ISSUE TITLE
Sending wrong active parameter in signatureHelp

### ISSUE THREAD

**Issue by oblitum** [saibing/bingo#20]
Just built the project and trying it out with coc.nvim,  for this simple code:

```go
package main

func foo(a, b int) int {
	return 42
}

func main() {
	foo(
}
```

On `foo(`, I get wrong signatureHelp highlight, it highlights the last parameter `foo(a int, *b int*)`, then when I insert the first integer, `foo(4, `, signatureHelp information returns the first parameter as active. I've checked the server communication.

**Comment by oblitum** [comment]
It also seems that for standard packages signatureHelp isn't working at all.

**Comment by oblitum** [comment]
> @oblitum
> 
> > It also seems that for standard packages signatureHelp isn't working at all.
> 
> Do you mean built-in functions(append, println...)?

I meant from standard packages, like `fmt`. They're responding now, but see below.

> > On `foo(`, I get wrong signatureHelp highlight, it highlights the last parameter `foo(a int, *b int*)`, then when I insert the first integer, `foo(4, `, signatureHelp information returns the first parameter as active. I've checked the server communication.
> 
> @oblitum
> 
> I have fixed this bug.

It's still not working for me, same behavior. Standard package's completion is responding but I get the same fuzzy behavior regarding signatureHelp highlight.

**Comment by oblitum** [comment]
In late protocol you can have `labelOffsetSupport` too, but it won't make any difference since you would have to support clients that ignore it too. In any case, that's just additional information, the signatureHelp's current parameter bug could be present in whatever case if indexing is not done correctly.

**Comment by oblitum** [comment]
Relevant log for the original example code.

On opening parentheses (`foo(`):

```
[Trace - 4:12:54 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 5,
        "uri": "file:///home/francisco/Projects/samples/go/sample.go"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 7,
                    "character": 4
                },
                "end": {
                    "line": 7,
                    "character": 4
                }
            },
            "rangeLength": 0,
            "text": "("
        }
    ]
}

[Trace - 4:12:54 PM] Sending request 'textDocument/signatureHelp - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///home/francisco/Projects/samples/go/sample.go"
    },
    "position": {
        "line": 7,
        "character": 5
    }
}

[Trace - 4:12:54 PM] Received response 'textDocument/signatureHelp - (2)' in 68ms.
Result: {
    "signatures": [
        {
            "label": "foo(a int, b int)",
            "parameters": [
                {
                    "label": "a int"
                },
                {
                    "label": "b int"
                }
            ]
        }
    ],
    "activeSignature": 0,
    "activeParameter": 1
}
```

On first comma (`foo(1,`):

```
[Trace - 4:12:57 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 7,
        "uri": "file:///home/francisco/Projects/samples/go/sample.go"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 7,
                    "character": 6
                },
                "end": {
                    "line": 7,
                    "character": 6
                }
            },
            "rangeLength": 0,
            "text": ","
        }
    ]
}

[Trace - 4:12:57 PM] Sending request 'textDocument/signatureHelp - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///home/francisco/Projects/samples/go/sample.go"
    },
    "position": {
        "line": 7,
        "character": 7
    }
}

[Trace - 4:12:57 PM] Received response 'textDocument/signatureHelp - (4)' in 34ms.
Result: {
    "signatures": [
        {
            "label": "foo(a int, b int)",
            "parameters": [
                {
                    "label": "a int"
                },
                {
                    "label": "b int"
                }
            ]
        }
    ],
    "activeSignature": 0,
    "activeParameter": 0
}
```

**Comment by saibing** [comment]
@oblitum 
I'm sorry. I can't reproduce the above problem in vscode. Can you reproduce it in vscode?

**Comment by oblitum** [comment]
Sorry but I don't use vscode. Though, I think this is a bingo issue, since it's the one that's clearly sending wrong activeParameter, maybe it's getting lost the way messages are sent from client. I'm currently using [coc.nvim](https://github.com/neoclide/coc.nvim), bingo is the only server that reproduces this behavior.

**Comment by oblitum** [comment]
Notice the above output isn't full, I get interleaved diagnostics reports, I've cut it because the message is too noisy and would probably not be relevant.

**Comment by saibing** [comment]
@oblitum 

I have fixed this bug, please try the latest version bingo

**Comment by oblitum** [comment]
@saibing thanks, it's working now.
