### ISSUE TITLE
configuring formatting/linting

### ISSUE THREAD

**Issue by dbarrosop** [saibing/bingo#26]
Hello,
let me start by saying this is awesome work. I have a couple of questions regarding formatting/linting (for reference I am using neovim with your sample configuration):

1. Is it possible to configure the formatting command? With `vim-go` I was using `goimports`. As I am looking to fully migrate to `bingo`, can I do the same?
2. Is it possible to configure how often the language-server tries to lint the code? Right now it is too often, which leads to constant errors (as soon as you type a key it will complain that letter is not defined) and lots of CPU usage. Instead I'd prefer to do it on events (like saving the buffer). This might be a question though to the language server plugin, not sure about that.
3. Is it possible configure the linter used? I am using gometalinter with neomake today and I'd love to be able to do the same here.

Thanks!

**Comment by oblitum** [comment]
@dbarrosop On 2, I use bingo with coc.nvim and there's no such it's, I think it provides a good balance, it doesn't happen on every character input, but happens on hold, or going to normal mode, etc, which I find better than simply on save. Yes, I think it's an issue/configuration of the language server client.

**Comment by saibing** [comment]
@dbarrosop 
1. you can set "--format-style" to choice "goimports"
2. you can set "---disable-diagnostics" to disable server's diagnostics
3.bingo does not support it by far

**Comment by saibing** [comment]
@dbarrosop 

I have changed diagnostics go file on  saving the buffer.

**Comment by oblitum** [comment]
@saibing seriously? I've changed to bingo from go-langserver mainly because I wished to avoid diagnostics-only-on-save that's also provided there, and often failed to update them. It's also the reason behind [this behavior](https://github.com/w0rp/ale/issues/2124) in some editors.

That's not in general the default behavior throughout LSP servers I use, can't it be provided behind a flag?

**Comment by dbarrosop** [comment]
Thanks! This is great :)

**Comment by saibing** [comment]
@dbarrosop 

I have no plans to call golint and other tools in bingo, because golint, go vet can be integrated directly in the editor.

**Comment by dbarrosop** [comment]
No problem, I will keep using neomake for linting and bingo for the rest, thanks again!
