### ISSUE TITLE
completion returns snippet in nvim

### ISSUE THREAD

**Issue by imjustfly** [saibing/bingo#30]
I use nvim with LanguageClient-neovim, and completion wrongly returns snippet:

```golang
import "fmt"

func main() {
		fmt.Println(${1:a ...interface\{\}})  // completion returns the snippet.
}
```

I am not sure whether it's a bug of bingo or LanguageClient-neovim.

**Comment by imjustfly** [comment]
Actually, there is already a switch for this feature --  `-func-snippet-enabled`. But as a boolean flag, its default value is true,  this means you must disable it by setting `-func-snippet-enabled=false`.

How about changing this flag's name to `-disable-func-snippet` and make its default value to false? This makes this flag easy to use and the same form as other boolean flags, such as `-disable-diagnostics` and `-use-global-cache` etc.

By the way, is this the lsp's standard way to send the snippet with completion? If so, LanguageClient-neovim should support this format.

**Comment by fannheyward** [comment]
@imjustfly Yes, this is the standard of LSP, you can try [coc.nvim](https://github.com/neoclide/coc.nvim), which support almost full LSP features. https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#improve-completion-experience

With the function snippets feature enabled, your example above will become `fmt.Println(|)`, where `|` is the cursor.

**Comment by saibing** [comment]
@imjustfly 

I have changed the flag -func-snippet-enabled to -disable-func-snippet

**Comment by imjustfly** [comment]
@fannheyward thanks. I will have a try.

**Comment by rraks** [comment]
In python language server, a completion suggestion does not return a snippet, but a snippet command (for eg a request by neosnippet for a snippet) returns the snippet. 
Currently for me, every suggestion is returning back a snippet. 
How do i disable this, and get a snippet only when i ask for it.
