### ISSUE TITLE
对于大工程，补全的速度还是不行

### ISSUE THREAD

**Issue by Cosson2017** [saibing/bingo#35]
对于大工程，补全的速度还是不行。

**Comment by saibing** [comment]
代码量多大的工程？补全响应大概要多长时间？

**Comment by saibing** [comment]
@Cosson2017 

我对这种场景进行了一些优化：第一次把该package文件读入内存, 后续不会每次从磁盘读取300个文件, 你测试一下最新版本,看一下速度是否有提升.

**Comment by Cosson2017** [comment]
@saibing 我元旦后去公司试试

**Comment by Cosson2017** [comment]
@saibing 稍微好一点了 但是还是有3秒左右的延迟

**Comment by seagle0128** [comment]
真的还是太慢了~~~~

**Comment by saibing** [comment]
@Cosson2017 @seagle0128 
你们电脑磁盘的性能怎么样？是SSD？还是机械硬盘？或者是云桌面的共享磁盘？

我在个人个机械硬盘的台式机Ubuntu上还是比较快的, 大概1秒以内

如果是云磁盘就比较慢了, 我在公司的云桌面电脑上就很卡.

**Comment by Cosson2017** [comment]
我的是台式的arch 机械硬盘

**Comment by saibing** [comment]
@Cosson2017 @seagle0128 
请下载一下最新的bingo, 增加如下参数：
```bash
["--golist-duration", "30"]
```

看一下补全的性能是否有提升？

**Comment by seagle0128** [comment]
新版本加不加这个参数都有很大提升。我会继续测试。谢谢！

**Comment by PendragonSaber** [comment]
@saibing  咦这个server是国人fork的？这个server和go-langserver有什么区别吗？gocode在1.10以后表现的很糟糕准备切换lsp。日常编辑器vim

**Comment by saibing** [comment]
@PendragonSaber 

[Differences between go-langserver, bingo, golsp](https://github.com/saibing/bingo/wiki/F.A.Q)

The main difference is that bingo support go module project.

**Comment by saibing** [comment]
duplicated with #22
