### ISSUE TITLE
automatically compute module root directory

### ISSUE THREAD

**Issue by fhs** [saibing/bingo#38]
Currently if I set RootURI to `file:///`, bingo takes some time to scan all files in / and then gives this error:
```
LSP Error: / is out of GOPATH workspace [/home/fhs/go], but not a go module project
```
Doing the scan before showing the error is a separate issue. The reason that `file:///` might be passed as RootURI is because many editors (e.g. vim, acme) don't have an "open folder" or "project directory" that would normally be used as the RootURI. Relying on LSP clients to set the correct RootURI requires them to have extra logic for each language, which goes against the goals of LSP. There is ongoing discussion here: https://github.com/golang/go/issues/29174  and 
https://groups.google.com/forum/#!topic/golang-tools/3f-GPF91B2c.  In particular, this comment describes how LSP goals are violated: https://github.com/golang/go/issues/29174#issuecomment-446923751.

I'm proposing that if RootURI is invalid, bingo should figure out the RootURI based on the first incoming requests. For example, if that request is a go-to-defenition request in file /a/b/foo/bar.go and there is a /a/b/go.mod file, bingo can search for the go.mod file and determine /a/b as the RootURI. If go.mod file is missing, it can fallback to checking $GOPATH.

The go tool already does something like that as far as I know, so I'm failing to understand why bingo doesn't do something similar.

**Comment by fhs** [comment]
@saibing My go module full path is deeper than 4-level somewhere in $HOME. My point was bingo shouldn't assume RootURI points to a module directory and start scanning it because the LSP client may know nothing about Go.

**Comment by saibing** [comment]
@fhs 

please try the latest version, I have make bingo more robust against this kind of problem.

**Comment by fhs** [comment]
@saibing Bingo is still scanning all files in RootURI. It's taking a very long time do even a simple go-to-definition because I guess it's busy caching my whole filesystem. I was hoping for bingo to cache modules on-demand instead once at the beginning.

**Comment by saibing** [comment]
@fhs 
I have added a new flag:

```bash
  -cache-style string
    	set global cache style: none, on-demand, always. Can be overridden by InitializationOptions. (default "always")
```

you can set  ['--cache-style', 'on-demand'] to disable global cache when bingo startup.

**Comment by fhs** [comment]
Thanks @saibing !
`-cache-style none` works for me, although I think there are issues when `GO111MODULE=on`:
```
$ GO111MODULE=on winid=77 L -server '.*:bingo -cache-style none' refs
LSP Info: load / successfully! elapsed time: 0 seconds, cache: false, go module: false.
2019/01/23 10:03:25 jsonrpc2: code 0 message: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- /home/fhs/go/src/github.com/rjkroege/edwood]: exit status 1: go: cannot find main module; see 'go help modules'
```

I think `-cache-style on-demand` will be useful for me when caching is done per-module instead of one global cache.

**Comment by saibing** [comment]
@fhs 
if set GO111MODULE=on, go command only support go module project.

**Comment by fhs** [comment]
@saibing This particular project has a go.mod file but it's also in $GOPATH, so I have to set GO111MODULE=on to force it to be a module.

Anyway, if I run
```
GO111MODULE=on go list -e -json -compiled -test=true -export=false -deps=true -find=false -- /home/fhs/go/src/github.com/rjkroege/edwood
```
within the module directory, it's successfully prints the json output. However, if my current working directory is outside of the module directory, the command fails. So, I think bingo might not be setting the current  working directory correctly.

This is how the main module is defined by the go command:
```
$ go help list | grep 'current dir'
The main module is the module containing the current directory.
```

**Comment by saibing** [comment]
@fhs 

I have test $GOPATH/src/github.com/rjkroege/edwood project with latest bingo is ok:

```bash
--cache-style="on-demand'
GO111MODULE=on
```

**Comment by fhs** [comment]
Great work! `-cache-style on-demand` is working correctly now. Only issue is `-cache-style none` does not print out all the references. It's only giving the definition of the identifier, leaving out where it's used.
```
$ GO111MODULE=on winid=17 L -server '.*:bingo -cache-style none' refs
LSP Info: load / successfully! elapsed time: 0 seconds, cache: false, go module: false.
References:
 /home/fhs/go/src/github.com/rjkroege/edwood/text.go:1421:16-1421:26
$ GO111MODULE=on winid=17 L -server '.*:bingo -cache-style on-demand' refs
LSP Info: load / successfully! elapsed time: 0 seconds, cache: false, go module: false.
References:
 /home/fhs/go/src/github.com/rjkroege/edwood/text.go:1379:18-1379:28
 /home/fhs/go/src/github.com/rjkroege/edwood/text.go:1395:18-1395:28
 /home/fhs/go/src/github.com/rjkroege/edwood/text.go:1421:16-1421:26
```

(Note: L command is from https://github.com/fhs/acme-lsp)
