### ISSUE TITLE
unrecognized import path "golang.org/x/sys

### ISSUE THREAD

**Issue by xianghx** [saibing/bingo#39]
HI, thanks your work.
网上的方法试过了， 手动下了，放在golangx.org/x/ ,  但还是没解决。想问下该怎么解决？谢谢。

~/go/src/github.com/bingo$ GO111MODULE=on go install
go: golang.org/x/sys@v0.0.0-20181212120007-b05ddf57801d: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 64.233.162.81:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181220203305-927f97764cc3: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 64.233.162.81:443: i/o timeout)
go: error loading module requirements

go version
go version go1.11.4 linux/386

**Comment by saibing** [comment]
@xianghx 
请设置一下第三库下载代理：
export GOPROXY=https://athens.azurefd.net/
如果是Windows操作系统,请设置一下环境变量GOPROXY=https://athens.azurefd.net/

需要重新启动一下shell或cmd.exe

**Comment by xianghx** [comment]
非常感谢， 很好用。 建议写进readme, 方便中国用户使用。我关闭了。

**Comment by xuyao91** [comment]
Mac电脑，这样设置了，还是没有用。
