### ISSUE TITLE
Could not find packages. Ensure `gopkgs -format {{.Name}};{{.ImportPath}}` runs successfully.

### ISSUE THREAD

**Issue by hujianxin** [saibing/bingo#48]
你好，我遇到一个问题。

在使用最新版vscode（Version: 1.30.1）+bingo时，补全跳转都没问题，但是保存文件时，不自动导入包，而是报题目中所显示的问题。

请问这是我的配置问题还是其他问题呢？

**Comment by hujianxin** [comment]
在gopath之外的go module项目之中。go版本是go1.11.1，系统是Ubuntu16.04

谢谢

**Comment by hujianxin** [comment]
This information is not displayed on my macbook, but it can alse not autoimport, is it a feature?

**Comment by saibing** [comment]
@hujianxin 
请参考如下方式设置vscode的参数：

```json
{
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "bingo"
    },
    "go.languageServerFlags": ["--trace", "--format-style", "goimports"],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
}
```

这样保存文件时自动导入包.

**Comment by saibing** [comment]
duplicated with #53
