### ISSUE TITLE
format content bug

### ISSUE THREAD

**Issue by marlonfan** [saibing/bingo#50]
![](https://files.gitter.im/marlonfan/2uka/image.png)

当我格式化文末内容时,如果按照 bingo 给出的提示, 会在末尾留一个空行, 这与gofmt期望的结果不符合;

**Comment by saibing** [comment]
@marlonfan 

怎么重现这个问题？我这边使用vscode无法重现它.

**Comment by marlonfan** [comment]
@saibing 

1. 开启vscode的lsp的trace功能
2. 打开任意一个符合go语法的go文件
3. 在末尾输入两个回车,看控制台的输出

**Comment by saibing** [comment]
Microsoft/vscode#67230

**Comment by saibing** [comment]
Microsoft/vscode-go#2279
