### ISSUE TITLE
auto import used and remove unused packages

### ISSUE THREAD

**Issue by zwpaper** [saibing/bingo#53]
Hi, Thanks for the project

When using, I found that there is no support for auto import used and remove unused packages.

It should be a good feature when writing Go

I was wondering whether there is a plan for this?

if help needed, I can try to help to implement this.

**Comment by anjmao** [comment]
I agree, that would be super useful. As bingo uses go tools package already there is a package for adding missing imports https://github.com/golang/tools/blob/master/imports/imports.go#L47:6 which may help in solving this, but I'm not sure which part of LSP should handling autoimports, probably that should be implemented under format logic.

**Comment by saibing** [comment]
@zwpaper @anjmao 

bingo already supports goimports style formatting,  please set bingo's startup parameter --format-style="goimports".  

it will auto import used and remove unused packages when formatting code
