### ISSUE TITLE
Autocomplete unimported packages

### ISSUE THREAD

**Issue by anjmao** [saibing/bingo#54]
One of the most needed feature which I missed from using vscode-go without lsp is being able to get autocompletion for unimported packages. Ideally typing `fmt.` should show autocompletion even if fmt package is not imported and after I select completion item it should add that import. Currently it is possible to get autoimport only if full expression is provided. For example I get import only if I write `fmt.Print` and hit save.

**Comment by antonkuzmenko** [comment]
I'm so lacking this feature :cry:
@anjmao it works after saving because `goimports` imports the `fmt` package. After the package is imported autocompletion works fine.
It's so sad that vs code is superior to vim in code completion in 2019

**Comment by phux** [comment]
Try this as a cheap workaround:
```
inoremap . .<esc>h:exec "silent GoImport ".expand("<cword>")<cr>la
```

**Comment by inliquid** [comment]
That's great! Thank you.

**Comment by fcying** [comment]
this feature can not support 3rd modules?

**Comment by antonkuzmenko** [comment]
@saibing this is so :money_mouth_face:
