### ISSUE TITLE
没有补全提示

### ISSUE THREAD

**Issue by PendragonSaber** [saibing/bingo#57]
正常安装了。但是在编辑文件时并没有提示，使用coc是有效的，但是我切换LanguageClient-neovim并没有生效，使用go-langserver是正常的，如何debug它是否在工作？
最小init.vim
```
 let g:deoplete#enable_at_startup = 1
   
  set hidden
  let g:LanguageClient_rootMarkers = {
           \ 'go': ['.git', 'go.mod'],
           \ }
    
   let g:LanguageClient_serverCommands = {
       \ 'go': ['bingo', '--format-style', 'goimports'],
     \ }
```

**Comment by PendragonSaber** [comment]
它工作了，但是我需要按下c-x c-o才能提示，补全插件deoplete是已经接管了omi的，但是不能一起工作，go-langserver是正常的

**Comment by PendragonSaber** [comment]
![2233333334](https://user-images.githubusercontent.com/41671631/51084970-9e868180-176d-11e9-9ab2-cdda245f4f49.png)
虚拟机里重装了个linux测试 提示这个错误

**Comment by saibing** [comment]
@PendragonSaber 

第一个问题，比较奇怪，我使用LanguageClient-neovim + [ncm2](https://github.com/ncm2/ncm2)，是ok的。

第二个问题，目前是需要选择到$GOPATH/src/<subdir>这级目录，不支持打开$GOPATH/src目录

**Comment by PendragonSaber** [comment]
> @PendragonSaber
> 
> 第一个问题，比较奇怪，我使用LanguageClient-neovim + [ncm2](https://github.com/ncm2/ncm2)，是ok的。
> 
> 第二个问题，目前是需要选择到$GOPATH/src/<subdir>这级目录，不支持打开$GOPATH/src目录

@sabing  ok 我在测试一下。

**Comment by PendragonSaber** [comment]
> > > @PendragonSaber
> > > 第一个问题，比较奇怪，我使用LanguageClient-neovim + [ncm2](https://github.com/ncm2/ncm2)，是ok的。
> > > 第二个问题，目前是需要选择到$GOPATH/src/这级目录，不支持打开$GOPATH/src目录
> > 
> > 
> > @sabing ok 我在测试一下。
> 
> 我感觉我配置是哪里出错了，但是我找不到。我的mac和虚拟机里的linux 都不能获得相关功能。我需要初始化一个gomod项目吗？我直接在gopath下新建一个项目是不成功的，我配置的过程在~目录下执行git拉取，然后cd bingo  开启gomod执行go install，在gopath的bin目录下生成了bingo文件。是哪里出了问题吗

**Comment by PendragonSaber** [comment]
我吧bingo的二进制文件在终端执行一遍，我就可以得到补全了。
