### ISSUE TITLE
本地写的包不能补全

### ISSUE THREAD

**Issue by taigacute** [saibing/bingo#58]
自己写的包不能提示补全，而且标准库的补全在我这里有的文件可以有的文件不可以。我搞不清楚发生了什么，有没有debug的方法？我会通过coc的debug测试一下。我用go-langserver是一切正常的
![ulite](https://user-images.githubusercontent.com/41671631/51179161-b68e0a80-18ff-11e9-8704-1dbc4e92035f.gif)

**Comment by PendragonSaber** [comment]
> @PendragonSaber
> 
> 你的是go module工程，还是传统的go path工程？
> 
> 另外在根目录下go build是否ok?

@saibing  gopath 不是gomod工程，而且这个补全时有时无，很奇怪。我在mac工程机和linux ubutn manjaro都测试了 。我觉得安装应该没什么问题，搭的梯子也都安装完的。生成.a文件吗？bingo也是需要找.a文件来获得补全吗

**Comment by saibing** [comment]
请增加 "--trace", "--logfile", "/tmp/bingo.log"调试一下, 看一下bingo是否返回正确的补全信息.

**Comment by taigacute** [comment]
> @taigacute
> 
> 请下载最新版本的bingo试一试, 补全功能是否正常？

好的 我试一下

**Comment by taigacute** [comment]
@saibing  我切换到了go-langserver在切换回来bingo 它又工作了。
![334](https://user-images.githubusercontent.com/41671631/51436800-f887c980-1cce-11e9-9be9-a91bd513bda9.png)
但是我在新建一个项目，它又不会工作
![44](https://user-images.githubusercontent.com/41671631/51436825-53212580-1ccf-11e9-8381-f40a5032f358.png)

**Comment by saibing** [comment]
@taigacute 

![image](https://user-images.githubusercontent.com/5676390/51437486-04c55400-1cda-11e9-9685-6d1a53b18680.png)

Can you see the bingo's notify message when it startup successfully?

**Comment by saibing** [comment]
@taigacute 

![image](https://user-images.githubusercontent.com/5676390/51437616-9ed9cc00-1cdb-11e9-9c57-9a057ef1e44d.png)

我这边试用了一下coc.nvim, 配合bingo使用是正常的？

**Comment by taigacute** [comment]
> @taigacute
> 
> ![image](https://user-images.githubusercontent.com/5676390/51437616-9ed9cc00-1cdb-11e9-9c57-9a057ef1e44d.png)
> 
> 我这边试用了一下coc.nvim, 配合bingo使用是正常的

1.我是可以看到启动成功
2.我在虚拟机装了2个linux  ubuntu和manjaro  包括本机mac  都没成功过。
3.使用go-langserver正常
安装步骤：
1.~目录下git clone 
2.cd  bingo
3. 开启gomod  go install  挂着梯子全部执行。没有任何错误

**Comment by taigacute** [comment]
在gopath目录下新建工程bingo都是不起作用的，但是偶尔又可以。我搞不清楚发生了什么。我测试了一下。如图这样的目录bingo没有起作用
![234](https://user-images.githubusercontent.com/41671631/51439102-5bd62380-1cf0-11e9-9dec-29ca250f4dd7.png)
我操作gopath外目录的工程例如我写bingo下的doc.go 它是正常工作的
![Uploading 234.png…]()

**Comment by taigacute** [comment]
我自己创建了一个go mod 工程。失败
![1](https://user-images.githubusercontent.com/41671631/51439236-3b0ecd80-1cf2-11e9-8b6a-c4d8b4d80df3.png)

**Comment by saibing** [comment]
@taigacute 

新创建的工程的确这个问题. 这是因为--golist-duration缓存导致的, 为了提升补全的性能.我缓存了go list命令的结果. 但对于新的工程来说缓存--golist-duration是无效的：因为新创建的http2.go还没来得急写完package xxx.

你可以先把golist缓存关闭掉：["--golist-duration",  0]

对于已经创建的package没有问题.

**Comment by saibing** [comment]
@taigacute 

默认设置--golist-duration = 0规避该问题. 如果启用了--golist-duration, 机制上会导致该问题, 无法解决
