### ISSUE TITLE
保存文件时，有时候不能自动导入依赖

### ISSUE THREAD

**Issue by hujianxin** [saibing/bingo#59]
配置如下：
```
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "bingo"
    },
    "go.languageServerFlags": ["--trace", "--format-style", "goimports"],
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true
    },
```

go version: go1.11 darwin/amd64

在gopath之外的go mod项目

谢谢

**Comment by hujianxin** [comment]
刚重启了code的时候，会自动导入缺少的依赖（goimports），但是后来就不行了，必须重启code

**Comment by saibing** [comment]
请看一下保存的时候, 有没有调用textDocument/formatting, 它返回的结果是什么？正常工作日志如下图：
![image](https://user-images.githubusercontent.com/5676390/51394457-691ad300-1b75-11e9-8547-eee26246a4cd.png)

**Comment by saibing** [comment]
@hujianxin 

请下载最新版本的bingo试用一下,看一下自动导入功能是否正常？

**Comment by hujianxin** [comment]
应该是fix掉了。不过我的Output里面啥也没显示。多谢

**Comment by saibing** [comment]
@hujianxin 

没有配置"--trace"的参数？

**Comment by hujianxin** [comment]
我的配置就是上面第一条贴的那个，--trace参数应该是这样配置吧？

**Comment by saibing** [comment]
@hujianxin 

![image](https://user-images.githubusercontent.com/5676390/51438692-570e7100-1cea-11e9-81b9-e9207882a8d1.png)

启动成功后,有没有看到类似上面的通知信息？

**Comment by hujianxin** [comment]
![image](https://user-images.githubusercontent.com/9526904/51439426-f3d60c00-1cf4-11e9-84ec-e4c74a8d2ba7.png)

这个确实有

**Comment by hujianxin** [comment]
@saibing 好的，多谢，如果有后续发现，我再反馈。
