### ISSUE TITLE
没办法进去类型定义。。其他速度是挺快的

### ISSUE THREAD

**Issue by imxyb** [saibing/bingo#6]

**Comment by saibing** [comment]
@imxyb 

请举一个详细的例子
please give an example.

**Comment by imxyb** [comment]
貌似用了新版本可以了，可惜就是必须开go mod，我现在主要开发项目不是go mod的。原来vscode那个go-langsever简直太差了，寻找一个implement都要好久

**Comment by saibing** [comment]
Hi @imxyb 
很高兴的告诉您，bingo已经初步支持非go module工程（即传统的GOPATH工程），目前是体验状态，你可以安装最新版本测试一下。请参考：saibing/bingo#5

我也是实在无法忍受go-langserver性能，所以才在它的基础上进行改造，诞生一个新的language server，因为我完全是业余时间在支持这个项目，所以测试工作进行得不是非常充分，使用过程中，会存在一些bug, 如果有什么问题，可以通过创建issue的方式反馈给我。
