### ISSUE TITLE
Diagnostics not displayed on text change

### ISSUE THREAD

**Issue by felix-d** [saibing/bingo#60]
I'm using Neovim with [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) and for a reason I ignore, linter diagnostics are not displayed on the fly. They are only displayed when I write the buffer. 

Any idea what I am missing here? It seems like this could be a language server implementation detail as other language servers I'm using (such as Rust Language Server) do lint when the document changes.

**Comment by saibing** [comment]
@felix-d 

you need set flag: --diagnostics-style=instant

**Comment by felix-d** [comment]
Thank you! Is this documented somewhere? I feel bad I had to open an issue for this.

**Comment by saibing** [comment]
@felix-d 

I'm sorry for this, I will add more detail document as soon as possible.

**Comment by felix-d** [comment]
No need to be sorry! Thanks for your help!

**Comment by oblitum** [comment]
IMO, the default should be instant, [not diagnostics-only-on-save](https://github.com/saibing/bingo/issues/26#issuecomment-451667295), few LSP servers do diagnostics-only-on-save by default. To be honest, bingo is the sole one I use that does it. At least there's the flag though.
