### ISSUE TITLE
Crashes in Atom after ide-go launches it

### ISSUE THREAD

**Issue by Starz0r** [saibing/bingo#61]
Atom seems launch the server then the process exits with Code 2 immediately after. I'm guessing somehow the client might invoke the process different than expected but seeing how it should be just a fork of [https://github.com/sourcegraph/go-langserver](go-langserver), it shouldn't be that hard to fix.

It looks like it crashes on a flag ```-format-tool```, but I can't entirely confirm as the Language Client isn't straight forward thanks to how Atom has structured their plugin architecture.

ide-go: https://atom.io/packages/ide-go

**Comment by saibing** [comment]
@Starz0r 

bingo has no '-format-tool' parameter, it support parameter's as follow:

```bash
Usage of bingo:
  -addr string
    	server listen address (tcp) (default ":4389")
  -diagnostics-style string
    	diagnostics style: none, instant, onsave. Can be overridden by InitializationOptions. (default "onsave")
  -disable-func-snippet
    	disable argument snippets on func completion. Can be overridden by InitializationOptions.
  -enable-global-cache
    	enable global cache when hover, reference, definition. Can be overridden by InitializationOptions.
  -enhance-signature-help
    	enhance signature help with return result. Can be overridden by InitializationOptions.
  -format-style string
    	which format style is used to format documents. Supported: gofmt and goimports. Can be overridden by InitializationOptions. (default "gofmt")
  -freeosmemory int
    	the interval time that aggressively free memory back to the OS, unit is second, default value is 0, means no free memroy back to the OS
  -golist-duration int
    	the interval of refresh the go list cache, unit: second, 0 means that does not use go list cache. Can be overridden by InitializationOptions.
  -logfile string
    	also log to this file (in addition to stderr)
  -maxparallelism int
    	use at max N parallel goroutines to fulfill requests. Can be overridden by InitializationOptions.
  -mode string
    	communication mode (stdio|tcp) (default "stdio")
  -pprof string
    	start a pprof http server (https://golang.org/pkg/net/http/pprof/)
  -trace
    	print all requests and responses
  -version
    	print version and exit
```

**Comment by Starz0r** [comment]
Yes, as I understand it, it's not a parameter, it's flag to a parameter, but I'm not sure which. The vanilla go-langserver seem to implement it, is it possible to have it in this project as well?

**Comment by saibing** [comment]
@Starz0r 
ckaznocha/ide-go#42

**Comment by saibing** [comment]
@Starz0r 

I'm very sorry, I don't have any plans to support [ide-go](https://github.com/ckaznocha/ide-go/issues/42), it seems to have stopped developing, so I am closing this issue here.

**Comment by Starz0r** [comment]
Is it possible to just add the `-format-tool` flag? It seems like the only thing that stops bingo from working with ide-go.
