### ISSUE TITLE
Add a way to exclude modules

### ISSUE THREAD

**Issue by yasushi-saito** [saibing/bingo#62]
It looks like bingo tries to find go.mod recursively under the root URI. Can we add a flag to exclude modules that match a certain regexp? It should be a simple change to Project.findGoModFiles.

The problem we are having is that we have some modules deep in our file system that are intentionally broken. That happens because we use a separate build system (bazel). 

But the way bingo is set up now, if any go.mod is broken, it won't serve anything. So I want to either (a) have a way to exclude modules manually, or (b) make bingo more robust against this kind of problem, and keep serving non-broken modules.

**Comment by saibing** [comment]
@yasushi-saito 

please try the latesr version,  I have make  bingo more robust against this kind of problem.

**Comment by saibing** [comment]
duplicated with #38
