### ISSUE TITLE
Can't find main module when project is opened as some upper-level folder

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#66]
Using VS Code.

`GOPATH=C:\Users\*****\go`
project is in `GOPATH`
`GO111MODULE=on`

When I open project as some upper-level folder containing module project, here is what happens in `go-langserver` output on hover:
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///c:/Users/*****/go/src/Enhancing_App_Communication_gRPC/m4-exercise-files") is deprecated. Use rootUri instead.
[Info  - 2:50:20 PM] notify: c:\Go\src\builtin is out of GOPATH workspace [C:\Users\*****\go], but not a go module project

[Info  - 2:50:20 PM] notify: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- Enhancing_App_Communication_gRPC/m4-exercise-files/...]: exit status 1: go: cannot find main module; see 'go help modules'


[Error - 2:50:36 PM] Request textDocument/hover failed.
  Message: context canceled
  Code: 0 
[Error - 2:50:43 PM] Request textDocument/hover failed.
  Message: context canceled
  Code: 0 
[Error - 2:50:43 PM] Request textDocument/hover failed.
  Message: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: cannot find main module; see 'go help modules'

  Code: 0 
[Error - 2:50:51 PM] Request textDocument/hover failed.
  Message: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: cannot find main module; see 'go help modules'

  Code: 0 
[Error - 2:50:51 PM] Request textDocument/hover failed.
  Message: context canceled
  Code: 0 
[Error - 2:50:52 PM] Request textDocument/hover failed.
  Message: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: cannot find main module; see 'go help modules'

  Code: 0 
```

However, when I open some sub-folder (still no `go.mod` at this level) it works, see the picture:
![3](https://user-images.githubusercontent.com/6797881/51438993-033d6100-1cc5-11e9-8fac-ca11e339e6af.png)

**Comment by saibing** [comment]
@inliquid 

Please set GO111MODULE=auto

if set GO111MODULE=on,  go command will treat the project under GOPATH as a go module project.

**Comment by inliquid** [comment]
Yes, I know, that's what I want. It's module project but located under `GOPATH`. The point is that it works fine when particular folder is selected, but if I select parent folder it fails. Other than that, the contents of those folders are the same.

**Comment by inliquid** [comment]
@saibing so f.e. 
when I open `demos` folder everything's fine
when I open `m4-excercise-files` (which contains `demos`), it fails

both are located within `GOPATH` of course
both contain `go.mod` somewhere in child folders

**Comment by inliquid** [comment]
This solution helped! Thank you!
