### ISSUE TITLE
Language server error with "open /dev/null: too many open files *os.PathError"

### ISSUE THREAD

**Issue by GimmyHchs** [saibing/bingo#67]
I'm using bingo as LSP server in emacs and everything works well.

LSP **was broken after** I update the source code and rebuild it.

the error appears after commit https://github.com/saibing/bingo/commit/95ba27549b1fe1b38eea0d6b09078fa74823f616

reproduce steps:
```
rm $GOPATH/bin/bingo  // remove old version bingo
git checkout 95ba27549b1fe1b38eea0d6b09078fa74823f616
GO111MODULE=on go install
```
then open emacs.
see errors:
```
load /path/to/project/root/ successfully! elapsed time: 5 seconds
notify: open  /path/to/project/submodule1/: too many open files
notify: open  /path/to/project/submodule2/: too many open files
....
Error from the Language Server: couldn’t exec ’go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]’: open /dev/null: too many open files *os.PathError (Unknown error)
```
if I checkout to https://github.com/saibing/bingo/commit/5963059ef41a42c6a7e88f3f5266f32182fbbb35
and rebuild again. Everything works well.

**Comment by saibing** [comment]
@GimmyHchs 

please update bingo to latest commit, and tell me the watch dir number as follow:

![image](https://user-images.githubusercontent.com/5676390/51441826-c5fec080-1d10-11e9-91ae-dabe2164eb00.png)

**Comment by GimmyHchs** [comment]
```
load /path/to/project/root/ successfully! elapsed time: 6 seconds, watch dir number: 52, cached: true
```

**Comment by GimmyHchs** [comment]
@saibing 
I could only reproduce this problem some of my projects.

close this issue until I found the pattern to reproduce.

thx!

**Comment by GimmyHchs** [comment]
@saibing 
I'm using macOS Mojave.

checking the number of opened files by proccess:
```
$ lsof -n|awk '{print $2}'|sort|uniq -c|sort -nr|more
```
![bingo-67-1](https://user-images.githubusercontent.com/11835351/51443531-0700d000-1d25-11e9-8009-268bd9e49e15.png)

- projectA -> error
- projectB -> error
- project go-langserver -> normal

1. **Add a lot of files** as Fake-Submodule into project go-langserver
2. Restart bingo-lsp server.

![bingo-67-2](https://user-images.githubusercontent.com/11835351/51443571-b5a51080-1d25-11e9-9d5e-ce216a946812.png)

- project go-langserver -> error

========================================
I think the bug appears because opening too many files for cache-features.  
and the number of opened files is too large so that exceed the range of my system.

**Comment by s-kostyaev** [comment]
Also have this issue on latest commit (Also macOS Mojave). I think the root of problem is https://github.com/fsnotify/fsnotify/issues/11 and https://github.com/piranha/gostatic/issues/76. So you can try use https://github.com/emcrisostomo/fswatch instead of github.com/fsnotify/fsnotify because it supports Apple OS X File System Events. @saibing  I can try to do this experiment at the weekend if you want.

**Comment by saibing** [comment]
@s-kostyaev 

I feel very happy, if you can help solve this problem. 

I don't have a Mac to test this problem.

**Comment by s-kostyaev** [comment]
Ok, I'll try.

**Comment by jguenther** [comment]
I also am intermittently getting this error in projects with lots of non-go files.

The one I was having trouble with the other day had a python virtualenv in it with a bunch of `.py` files, and from `lsof` output for the bingo process it had filehandles open for all of them

**Comment by mbana** [comment]
```sh
[Info  - 10:35:39 AM] notify: open /Users/mbana/work/openbankinguk/bitbucket/conformance-suite/web/node_modules/yorkie: too many open files
...
[Info  - 10:35:39 AM] fsnotify watch dir number: 1135
...
```

Confirming same issue on Mac.
