### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#69]
For example here is what VS Code displays for `os/signal` package

![default](https://user-images.githubusercontent.com/6797881/51446870-d9b62100-1d28-11e9-8e81-0cf63bd37421.png)

![default](https://user-images.githubusercontent.com/6797881/51446872-df136b80-1d28-11e9-8b0e-339ec218c90b.png)

**Comment by mbana** [comment]
Maybe use this package instead https://github.com/davecheney/godoc2md? However, I cannot get it to compile.

**Comment by saibing** [comment]
@inliquid @mbana 

Please use the enhanced version of [gopls](https://github.com/saibing/tools), it has fixed this issue
