### ISSUE TITLE
Diagnostics keeps showing even if I delete the error line.

### ISSUE THREAD

**Issue by imjustfly** [saibing/bingo#7]
Thanks for your great work !  

I use bingo in vim with LanguageClient-Neovim. And after I typed something wrong in a new line, the diagnostics shows in the gutter. But diagnotics keeps showing even if I fixed it or just delete the error line.

**Comment by anjmao** [comment]
1. Show variable as not used, but this compiles with go build.
![image](https://user-images.githubusercontent.com/3028012/49274965-98209c80-f482-11e8-9b42-f7721fb78234.png)

**Comment by saibing** [comment]
@imjustfly @anjmao 
I have fixed this first bug.

**Comment by saibing** [comment]
@anjmao 

How to reproduce the second question?

**Comment by imjustfly** [comment]
@saibing It works. Thanks!

**Comment by anjmao** [comment]
@saibing 

1. Create
```go
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

2. Now make invalid syntax, remove Println ending bracket

```go
package main

import "fmt"

func main() {
	fmt.Println("hello"
}
```

3. Now save the code

result
```go
package main

import "fmt"

func main() {
	fmt.Println("hello",
		BadExpr,
	)
}
```

**Comment by saibing** [comment]
@anjmao 

Thank you very much.

I have fixed the bug, please update to the latest version
