### ISSUE TITLE
Panic when viewing git diff in VS Code: slice bounds out of range

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#70]
This message 
`panic serving textDocument/hover: runtime error: slice bounds out of range`
only appears on hover at __left__ pane, _right_ continues working fine.

![default](https://user-images.githubusercontent.com/6797881/51448059-da54b480-1d34-11e9-9f20-78b0cada699b.png)

**Comment by saibing** [comment]
@inliquid 

```json
--> request #9: textDocument/hover: {"textDocument":{"uri":"git:/d%3A/git/go/source/hello/hello.go?
```

lsp server does not support "git:/" file path.
