### ISSUE TITLE
Can't find correct 'error' type definition.

### ISSUE THREAD

**Issue by inliquid** [saibing/bingo#76]
Tested with VS Code.

1. With quick documentation on hover it gives "invalid type" for `Error` interface method return value:
![default](https://user-images.githubusercontent.com/6797881/51943034-8e3afb80-2429-11e9-9fc5-675746cf56c5.png)
2. With 'go to definition' it points to some "error" word in comments of `builtin.go`:
![default](https://user-images.githubusercontent.com/6797881/51943096-b591c880-2429-11e9-87d5-43adc7c8e6d0.png)

**Comment by nezorflame** [comment]
Got the same issue on the latest master commit.
Also sometimes this happens with variables.

**Comment by mbana** [comment]
Still learning the code-base but I had a look at the `invalid type` being returned when hovering over `error`.

I added some logging to `langserver/hover.go`, see end of this comment.

**Note:**
In the log you will find this line `o=type error interface{Error() string}`. I wonder if there should be a special case for `Builtin` to use this value?

https://golang.org/src/go/types/object.go: 

```go
// A Builtin represents a built-in function.
// Builtins don't have a valid type.
type Builtin struct {
	object
	id builtinId
}
```

---

**Thoughts/Questions:**
* Does `vscode-go` handle this correctly when you are not using a Language Server?
* Does IntelliJ handle this correctly?

---

```bash
--> request #7: textDocument/hover: {"textDocument":{"uri":"file:///Users/mbana/dev/banaio/github/bingo/langserver/hover.go"},"position":{"line":97,"character":134}}
  params={TextDocument:{URI:file:///Users/mbana/dev/banaio/github/bingo/langserver/hover.go} Position:97:134}
  pathNodes[0]=error
    o=type error interface{Error() string}
    t=error
    p.IsValid()=false
    p=0
    pkg=type error interface{Error() string}
    o=type builtin.error interface{Error() invalid type}
    o.String()=type builtin.error interface{Error() invalid type}
    obj.Type()=builtin.error
    obj.Type().String()=builtin.error
    typ=interface{Error() invalid type}
    obj.Name()=error
    types.TypeString(typ, qf)=interface{Error() invalid type}
    comments=The error built-in interface type is the conventional interface for
representing an error condition, with the nil value representing no error.

    contents=[{Language:go Value:type error interface isRawString:false} {Language: Value:The error built-in interface type is the conventional interface for representing an error condition, with the nil value representing no error. 

 isRawString:true}]
    extra=interface {
    Error() invalid type
}
    contents=[{Language:go Value:type error interface isRawString:false} {Language: Value:The error built-in interface type is the conventional interface for representing an error condition, with the nil value representing no error. 

 isRawString:true} {Language:go Value:interface {
    Error() invalid type
} isRawString:false}]
<-- result #7: textDocument/hover: {"contents":[{"language":"go","value":"type error interface"},"The error built-in interface type is the conventional interface for representing an error condition, with the nil value representing no error. \n\n",{"language":"go","value":"interface {\n    Error() invalid type\n}"}],"range":{"start":{"line":97,"character":132},"end":{"line":97,"character":137}}}
```

**Comment by nezorflame** [comment]
@mbana yes, it does work in VSCode without bingo. Make sure you use `gogetdoc` since `godoc` doesn't show definition for built-in types and `guru` doesn't work with modules.

Attaching a screenshot to confirm this:
![image](https://user-images.githubusercontent.com/3906766/53302195-b7a24800-386c-11e9-8a5e-73c108fe6aca.png)
