### ISSUE TITLE
自动补全带参数的函数时后面多了一个0

### ISSUE THREAD

**Issue by guodongsoft** [saibing/bingo#79]
![2019-01-31 13 27 08](https://user-images.githubusercontent.com/4976988/52030682-4ec0fc00-255c-11e9-8b68-57b8d1d318e7.png)

回车后，20行的最后多了一个0。 (emacs开发环境)
![2019-01-31 13 27 50](https://user-images.githubusercontent.com/4976988/52030693-57b1cd80-255c-11e9-9f63-25e9f9bef4a4.png)

另外，能否让自动补全时，不区分大小写。
比如，输入下一个字符为大写W时有好几个选项，而小写w没有，一旦输入了w，智能提示窗就关闭了。因为只是选择而已，我认为没必要严格区分大小写。

**Comment by saibing** [comment]
![image](https://user-images.githubusercontent.com/5676390/52055549-ada56600-259a-11e9-8cc8-cad041d12226.png)

通过"."实现的函数补全应该是客户端实现的（如上的效果图）,因为服务端会把.所有的符号集返回，客户端实现过滤，目前coc.nvim, vscode是这么实现。

不是通过.补全，目前是区分了大小写的，主要时实现一个模糊的匹配算法需要一点时间，另外会损失性能，目前没有实现。

后面多了一个0感觉是emacs的lsp client处理有点问题，我使用coc.nvim, vscode编码没有这个问题。

**Comment by guodongsoft** [comment]
好的，明白了，谢谢！

**Comment by guodongsoft** [comment]
我用go-langserver没这个问题，按理说客户端是同一个，是不是返回的数据格式上有什么差别？我明天确认一下

**Comment by guodongsoft** [comment]
2月份开始，我要参加一个go项目的开发。C/C++,C#,Java我都有多年开发经验，所以编程能力没什么问题，但go我现在只看过两本入门级的书，想借助于参加的项目和你的bingo，来入手golang。看bingo的代码，从哪里开始入手比较好，在这之前我先看一下Lsp协议。除了，Readme推荐的资料外，你还有什么相关的推荐资料吗？

**Comment by saibing** [comment]
@guodongsoft 

从main.go开始：）其实主要熟悉go/ast, go/parser模块的代码与机制。
建议看一下：

[编程语言实现模式](https://book.douban.com/subject/10482195)

**Comment by guodongsoft** [comment]
好的，我刚才没问清楚，不过你回答清楚了。就是问那部分是重点的意思:)

多谢！

**Comment by saibing** [comment]
@guodongsoft 

我目前无法重现：自动补全带参数的函数时后面多了一个0, 先关闭该问题, 后续如果能重现, 我再分析解决.

**Comment by yydcnjjw** [comment]
在 `emacs` 的 `yasnippet`中, `$0` 表示片段的退出点
而 `bingo` 在 `emacs` 返回的片段中是 `${0}`
`yasnippet` 似乎会把它解析为带有默认值 `0` 的片段退出点

如
`fmt.Println(${1:a})${0}`

**Comment by guodongsoft** [comment]
谢谢，学习了
