### ISSUE TITLE
Use vendor first if exists.

### ISSUE THREAD

**Issue by imjustfly** [saibing/bingo#8]
Some `go.mod` users prefer generating a vendor directory and keeping it in vcs for some networking reasons. Can we use vendor first if vendor directory exists?

I know it may be difficult if `go/modules` doesn't consider vendor directory when loading modules. But I know little about the new `go/modules`, is this possible?

**Comment by saibing** [comment]
@imjustfly 

Now,  bingo support non-go module project,  so you can use vendor mode.
