### ISSUE TITLE
Auto-format joins lines

### ISSUE THREAD

**Issue by posniewski** [saibing/bingo#85]
When copy and pasting a line, the auto-formatter joins them. For example, a simple go program:
```
package main

func main() {
	var a int
	a = a
}
```
If I cut the `a = a` line and paste it above `var a int`, the result is:
```
package main

func main() {
a = a	var a int
}
```
I am doing a "cut line" (ctrl-x) with no selection. I then move the cursor to the first character of the `var a int` line and "paste" (ctrl-v). The line appears in the right place momentarily, and then gets auto-formatted and shows up as shown above.

This also occurs if you go to the line below, shift+up to select the line, ctrl-x to cut and then paste.
It does NOT happen if you select two or more lines and cut/paste.
The bug appears exactly the same if you copy rather that cut; when pasting, the line also gets joined.
I thought it might be LF vs CRLF, but it happens regardless of the line ending.
Setting `go.languageServerExperimentalFeatures { format: false }` makes the problem go away.
No messages appear in the go-langserver output log.

VSCode 1.30.2
Bingo commit 76b11e9c42686961395f4e0949d9c6ef25bd7b59

**Comment by vadimi** [comment]
I'm having the same issue in emacs with lsp-mode

**Comment by nezorflame** [comment]
Same issue, had to turn off formatting and use the default one from Go extension.

**Comment by saibing** [comment]
@posniewski

please try latest version bingo
