### ISSUE TITLE
emacs evil

### ISSUE THREAD

**Issue by guodongsoft** [saibing/bingo#88]
不知你有没有时间整一个emacs+evil的环境。

在编辑时，遇到一些奇怪的问题。比喻，我用dd命令删除一行，再移动光标到别的行，代码就乱了。

1. dd删除第63行
![2019-02-08 19 40 36](https://user-images.githubusercontent.com/4976988/52473643-a6550c80-2bd9-11e9-8ab5-1d3dfe20d87e.png)

2. 光标移动到56行
![2019-02-08 19 41 14](https://user-images.githubusercontent.com/4976988/52473646-ac4aed80-2bd9-11e9-87f6-4a58ea61dbcb.png)

出现的问题：
1. 54行变乱了
变化前：```param["pitch"] = *(v.Pitch)```
变化后：```param["pitch"] = *(v.Pitch)v.Pitch(v.Pitch)v.Pitch)```
※　在dd行删除操作之前，我做了```*v.Pitch => *(v.Pitch)```

2. 55行多了一个`}`

**Comment by guodongsoft** [comment]
上面现象可能与我的emacs的模式设定有关系。
不好意思，我先关闭这个issue。
另外，我想问一下，如何分析bingo和IDE之间通信的信息，或者哪里有log输出？

**Comment by saibing** [comment]
@guodongsoft 

设置一下bingo的启动参数：--trace, --logfile /tmp/bingo.log, 然后查看/tmp/bingo.log

**Comment by guodongsoft** [comment]
好的，谢谢！
