### ISSUE TITLE
这次非go mod能工作了，然而自动补全好像有点问题

### ISSUE THREAD

**Issue by imxyb** [saibing/bingo#9]
```json
 "go.useLanguageServer": true,
 "go.docsTool": "gogetdoc",
 "go.languageServerExperimentalFeatures": {
        "format": false,
        "autoComplete": true
 },
```
这是我的配置，现在我的自动代码提示出不来了，是啥回事呢

**Comment by saibing** [comment]
@imxyb 
你是在Windows下使用vscode吗? 因该是Windows路径风格导致的，我已经解决了，请下载新版本试一下。

**Comment by imxyb** [comment]
@saibing 我是mac的。我试试新版本

**Comment by imjustfly** [comment]
代码补全感觉相较于 go-langserver 来说延迟还是有点大，大项目更加明显，要等待几秒的时间。

**Comment by saibing** [comment]
代码补全跟磁盘性能相关。go-langserver采用的是从编译后.a文件中读取的，如果提前编译好了，速度会很快，但编译后，新增的代码无法实时联想出来。bingo是实时分析当前已经编辑过的文件（主要要调用有给外部命令go list)，速度会差一些。

但在SSD硬盘速度应该是可以接受的。你启用一下bingo的-disable-diagnostics开关，把实时的diagnostics关闭掉，看是否有提升？

**Comment by s-kostyaev** [comment]
Can we cache results somehow (in memory  perhaps) for speedup autocompletion?

**Comment by saibing** [comment]
@imjustfly @s-kostyaev 

我已经提升级自动补全的性能, 请下载最新版本试用一下.

I have upgraded the performance of auto-completion, please download the latest version to try it out.

**Comment by imjustfly** [comment]
@saibing 感谢！测试比以前有可以感知的性能提升，在我这里日常使用没有性能问题。
