### ISSUE TITLE
fails to autocomplete on windows

### ISSUE THREAD

**Issue by gencer** [saibing/bingo#90]
One of my projects has `libvips` and `magicmime` dependency. Without this, `go build` or `go run` will fail on windows because i do not have that environment on windows. As this is a linux-targeted project, however, I code on Windows.

bingo trying to build and complaining about libvips not found in pkg-config. On windows neither libvips is available neither pkg-config. **

** I have libvips binaries and include files for windows x64 (my environment). But I don't know how to tell bingo to use them. However, I do not have magicmime and go build manually exits immediately due to this. You can see magicmime message below.

`gocode` works perfectly.

This is full stack trace:

```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///d:/Go/src/distributer") is deprecated. Use rootUri instead.
[Info  - 21:28:54] GOPATH: [D:\Go\], import path: 
[Error - 21:28:56] Request textDocument/documentSymbol failed.
  Message: go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- d:\Go\src\distributer]: exit status 2: go build distributer/vendor/github.com/rakyll/magicmime: build constraints exclude all Go files in D:\Go\src\distributer\vendor\github.com\rakyll\magicmime
# pkg-config --cflags  -- vips vips vips vips
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
pkg-config: exit status 1

  Code: 0 

```

**Comment by saibing** [comment]
@gencer 

Unfortunately, I have no more ideas about this issue. Maybe you can refer to this article [How to install pkgconfig in windows](https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows) or use [msys2](https://www.msys2.org/)

**Comment by gencer** [comment]
@saibing, I have successfully managed to install libvips and also get rid of magicmime. All projects works fine with bingo.
