### ISSUE TITLE
CompletionItem documentation string

### ISSUE THREAD

**Issue by detvdl** [saibing/bingo#91]
Hello,

I was wondering if it's on the roadmap to add the appropriate documentation strings as an attribute to the `CompletionItem` struct.
Currently `company-lsp` for emacs uses this information to provide documentation _while_ completion candidates are being shown, which, at least in my personal case, helps quite a bit when exploring a language and/or library.

Currently I have added a crude, hacky version of such functionality in my own fork, but this is **very** far from idiomatic or correct, as I am only a novice at Go.

If this is not on the roadmap due to the ongoing developments of the official Go lsp server or personal reasons, feel free to close this issue at once.

**Comment by mbana** [comment]
I've got this implemented but I don't like the way I've done it.
See this PR: https://github.com/saibing/bingo/pull/130.

![Imgur](https://i.imgur.com/jk72NwP.png)

**Comment by mbana** [comment]
@detvdl, looks like this PR got merged https://github.com/saibing/bingo/pull/130.
Please try now.

**Comment by detvdl** [comment]
@mbana Sorry for the late reply, tried it out and works as expected, thanks for doing this! 😄 
Guess this issue can be closed now @saibing

**Comment by mbana** [comment]
Please close issue?
