### ISSUE TITLE
GoToDefinition and References do not work

### ISSUE THREAD

**Issue by exordium-frozen** [saibing/bingo#93]
Hi there!

After updating to latest version (commit `33a02d93cc41360161cf8d69fcbedc3c0a061fba`) Bingo doesn't work anymore in my setup.

I've tried to figure out which commit breaks it (since there are two identical setups, one is updated, the other stays on previous version of Bingo).
The commit `94c04cfc5fc3108584512cd27eaa936771648281` has broken things, the latest working is `a0b285f7dbbf1f77043583d44297b9dd9f8d7ba6`.

The setup:

- **OS** - `macOS Mojave 10.14.3`
- **Go** - `1.11.5`
- **GO111MODULE** - *not set*
- **Client** - `VS Code 1.31` and `VS Code 1.30`
- **vscode-go** - `0.8.0` and `0.9.2`
- Projects use **go modules**

Bingo Config:

```
"go.languageServerFlags": [
    "-format-style=gofmt",
    "-cache-style=on-demand",
    "-logfile=/tmp/bingo.log",
    "-trace",
],
```

Error messages when trying to use `GoToDefinition` or whatever:

```
--> request #26: textDocument/hover: {"textDocument":{"uri":"file:///path/to/file/foo.go"},"position":{"line":66,"character":17}}
<-- error #26: textDocument/hover: {"code":0,"message":"no packages found for /path/to/file/foo.go","data":null}
```

This happens for any file in a project, for both custom libraries and standard library.\
This also happens for any of my projects, so it does not depend on a project structure.

With Bingo complied using commit `a0b285f7dbbf1f77043583d44297b9dd9f8d7ba6` everything works as expected.

**Comment by saibing** [comment]
@exordium-frozen 

Please update the last version bingo and try again

**Comment by exordium-frozen** [comment]
@saibing 

Checked on one of my machines and it works.

Going to check on another one a bit later, it has more projects, and projects are larger.\
Once that done will be able to say whether the issue completely solved or not.

Thank you!

**Comment by saibing** [comment]
@exordium-frozen 

any update?

**Comment by exordium-frozen** [comment]
@saibing 

Just checked and it works.

Closing the issue.

Thank you!
